/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.sql.Date;
import java.text.SimpleDateFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import dao.DAO_ChucVu;
import dao.DAO_DichVu;
import dao.DAO_DichVuSuDung;
import dao.DAO_DonVi;
import dao.DAO_KhachHang;
import dao.DAO_LoaiDichVu;
import dao.DAO_LoaiPhong;
import dao.DAO_NhanVien;
import dao.DAO_PhieuThue;
import dao.DAO_Phong;
import entity.ChucVu;
import entity.DichVu;
import entity.DichVuSuDung;
import entity.DonVi;
import entity.KhachHang;
import entity.LoaiDichVu;
import entity.LoaiPhong;
import entity.NhanVien;
import entity.PhieuThue;
import entity.Phong;

/**
 *
 * @author admin
 */
public class GD_Chinh extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * Creates new form GD_Chinh
     */
    public GD_Chinh() {
        initComponents();
        setExtendedState(GD_Chinh.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
//    @SuppressWarnings("unchecked")
    ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource(".//images//logo.PNG"));
    private DefaultTableModel  modelDSPhongDat,modelDSDV, modelDSPT;
//    private String[] colsDSPhongTrong={"Mã phòng", "Tên phòng", "Loại phòng", "Giá"};
    private String[] colsDSPhongDat={"Mã PT","Tên Khách","Tên Phòng", "Loại Phòng", "Giá Phòng", "Ngày Nhận Phòng","Ngày Trả Phòng"};//
//    private String[] colsDSKH={"Mã KH","Tên Khách", "CMND/PASSPORT", "Số điện thoại"};
    private String[] colsDSDV={"Tên DV", "Ngày Đặt DV","Số Lượng","Đơn Vị Tính","Giá", "Thành Tiền"};
    
    private String[] colsDSPT={"Tên phòng","Loại Phòng","Giá"};
    
    public void DocDuLieuDatabaseVaoTableDSPhongDat() {
		ArrayList<PhieuThue> list = DAO_PhieuThue.getAllHoaDonPhongChuaThanhToan();
		modelDSPhongDat.setRowCount(0);
		for (PhieuThue hdp : list) {
			modelDSPhongDat.addRow(new Object[] {
					hdp.getMaPT(),
					getTenKH(hdp.getHoaDon().getKhachHang().getMaKH()),
					getTenPhong(hdp.getPhong().getMaPhong()),
					getTenLP(hdp.getPhong().getLoaiPhong().getMaLP()),
					getGiaLP(hdp.getPhong().getLoaiPhong().getMaLP()),
					new SimpleDateFormat("dd-MM-yyyy").format(new Date(hdp.getNgayDatPhong().getTime())),
					new SimpleDateFormat("dd-MM-yyyy").format(new Date(hdp.getNgayTraPhong().getTime())),
			});
		}
    }
    
    
    public void DocDuLieuDatabaseVaoTableDSDV() {
    	int i = tblDSPhongDat.getSelectedRow();
    	
    	try {
    		PhieuThue pt = new PhieuThue(Integer.parseInt(tblDSPhongDat.getValueAt(i, 0).toString()));
    		
        	ArrayList<DichVuSuDung> list = DAO_DichVuSuDung.getAllHDDV(pt.getMaPT());
        	
        		for (DichVuSuDung dv : list) {
        			modelDSDV.addRow(new Object[] {
        				getTenDV(dv.getDichVu().getMaDV()),
        				new SimpleDateFormat("dd-MM-yyyy hh:mm:ss a").format(new Date(dv.getGioDatDV().getTime())),
        				dv.getSoLuong(),
        				getTenDonVi(dv.getDichVu().getDonVi().getMaDonVi()),
        				dinhDangTienTe(getGiaDV(dv.getDichVu().getMaDV())),
        				dinhDangTienTe(dv.getSoLuong()*getGiaDV(dv.getDichVu().getMaDV()))
        			});
        		}
        	
		} catch (Exception e) {
			// TODO: handle exception
		}
    	
		
    }
    public void DocDuLieuDatabaseVaoDSPhong() {
    	ArrayList<Phong> listPhong = DAO_Phong.getALLPhongTrong();
    	for (Phong p : listPhong) {
    		modelDSPT.addRow(new Object[] {
    				
    				p.getTenPhong(),
    				getTenLP(p.getLoaiPhong().getMaLP()),
    				getGiaLP(p.getLoaiPhong().getMaLP())
    				});}
        }


    public String getTenLP(String maLP) {
    	ArrayList<LoaiPhong> listLP = DAO_LoaiPhong.getAllLoaiPhong();
    	for (LoaiPhong lp : listLP) {
    		if(lp.getMaLP().equalsIgnoreCase(maLP))
    			return lp.getTenLP();
    	}
    	return "";
    }
    
    public String getGiaLP(String maLP) {
    	ArrayList<LoaiPhong> listLP = DAO_LoaiPhong.getAllLoaiPhong();
    	for (LoaiPhong lp : listLP) {
    		if(lp.getMaLP().equalsIgnoreCase(maLP)) {
    			Locale localeVN = new Locale("vi", "VN");
    		    NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
    		    String giaLP = currencyVN.format(lp.getGiaLP());
//    			BigDecimal giaLP = new BigDecimal(lp.getGiaLP()).setScale(0, BigDecimal.ROUND_HALF_UP);
    			return giaLP;
    		}
    	}
    	return "";
    }
    
     String getTenPhong(String maPhong) {
    	ArrayList<Phong> listPhong = DAO_Phong.getAllPhong();
    	for (Phong p : listPhong) {
    		if(p.getMaPhong().equalsIgnoreCase(maPhong))
    			return p.getTenPhong();
    	}
    	return "";
    }
    
    String getTenKH(String maKH) {
    	ArrayList<KhachHang> list = DAO_KhachHang.getAllKhachHang();
    	for (KhachHang p : list) {
    		if(p.getMaKH().equalsIgnoreCase(maKH))
    			return p.getTenKH();
    	}
    	return "";
    }
    
    public String dinhDangTienTe(double tien) {
    	Locale localeVN = new Locale("vi", "VN");
	    NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
    	return currencyVN.format(tien);
    }
    
    public double getGiaDV(String maDV) {
    	ArrayList<DichVu> listDV = DAO_DichVu.getAllDichVu();
    	for (DichVu dv : listDV) {
    		if(dv.getMaDV().equalsIgnoreCase(maDV)) {
//    			BigDecimal giaLP = new BigDecimal(lp.getGiaLP()).setScale(0, BigDecimal.ROUND_HALF_UP);
    			return dv.getGiaDV();
    		}
    	}
    	return 0;
    }
    
    public String getTenDV(String maDV) {
    	ArrayList<DichVu> listDV = DAO_DichVu.getAllDichVu();
    	for (DichVu dv : listDV) {
    		if(dv.getMaDV().equalsIgnoreCase(maDV))
    			return dv.getTenDV();
    	}
    	return "";
    }
    
    public String getTenLoaiDV(String maLoaiDV) {
    	ArrayList<LoaiDichVu> list = DAO_LoaiDichVu.getAllLoaiDV();
    	for (LoaiDichVu ldv : list) {
    		if(ldv.getMaLoaiDichVu().equalsIgnoreCase(maLoaiDV))
    			return ldv.getTenLoaiDichVu();
    	}
    	return "";
    }
    
    public String getTenDonVi(String maDonVi) {
    	ArrayList<DonVi> list = DAO_DonVi.getAllDonVi();
    	for (DonVi donVi : list) {
    		if(donVi.getMaDonVi().equalsIgnoreCase(maDonVi))
    			return donVi.getTenDonVi();
    	}
    	return "";
    }
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem9 = new javax.swing.JMenuItem();
        pnlMain = new javax.swing.JPanel();
        pnlTTPT = new javax.swing.JPanel();
        btnTimPhongTrong = new javax.swing.JButton();
        txtTimPhongTrong = new javax.swing.JTextField();
        btnLamMoiPhongTrong = new javax.swing.JButton();
        lblDSPT1 = new javax.swing.JLabel();
        scrollDSPT = new javax.swing.JScrollPane();
        tblDSPT = new javax.swing.JTable();
        pnlChinh = new javax.swing.JPanel();
        btnThemDichVu = new javax.swing.JButton();
        scrollDSPDD = new javax.swing.JScrollPane();
        tblDSPhongDat = new javax.swing.JTable();
        lblDSPT2 = new javax.swing.JLabel();
        btnTim = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        scrollDSDV = new javax.swing.JScrollPane();
        tblDSDV = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        pnlBottom = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();
        lblTenNVLogin = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuPhong = new javax.swing.JMenu();
        Phong = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        DatPhong = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        QuanLyPhong = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        QuanLyLoaiPhong = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        menuDichVu = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        quanlyDV = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        quanLyLoaiDV = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        quanLyDonVi = new javax.swing.JMenuItem();
        menuKhachHang = new javax.swing.JMenu();
        quanLyKH = new javax.swing.JMenuItem();
        menuNhanVien = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        quanLyNhanVien = new javax.swing.JMenuItem();
        menuHoaDon = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        quanLyHoaDon = new javax.swing.JMenuItem();
        menuThongKe = new javax.swing.JMenu();
        tkBieuDo = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlTTPT.setBackground(new java.awt.Color(102, 204, 255));

        btnTimPhongTrong.setBackground(new java.awt.Color(204, 255, 255));
        btnTimPhongTrong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTimPhongTrong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTimPhongTrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimPhongTrongActionPerformed(evt);
            }
        });

        txtTimPhongTrong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimPhongTrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimPhongTrongActionPerformed(evt);
            }
        });

        btnLamMoiPhongTrong.setBackground(new java.awt.Color(204, 255, 255));
        btnLamMoiPhongTrong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLamMoiPhongTrong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLamMoiPhongTrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiPhongTrongActionPerformed(evt);
            }
        });

        lblDSPT1.setBackground(new java.awt.Color(102, 204, 255));
        lblDSPT1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDSPT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDSPT1.setText("DANH SÁCH PHÒNG ĐANG SỬ DỤNG");

        tblDSPT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã PT", "Tên Phòng", "Tên Khách", "Loại Phòng", "Giá Phòng", "Ngày Nhận Phòng", "Ngày Trả Phòng"
            }
        ));
        scrollDSPT.setViewportView(tblDSPT);

        javax.swing.GroupLayout pnlTTPTLayout = new javax.swing.GroupLayout(pnlTTPT);
        pnlTTPT.setLayout(pnlTTPTLayout);
        pnlTTPTLayout.setHorizontalGroup(
            pnlTTPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTPTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTTPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTTPTLayout.createSequentialGroup()
                        .addComponent(lblDSPT1)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(pnlTTPTLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlTTPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollDSPT, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(pnlTTPTLayout.createSequentialGroup()
                                .addComponent(btnLamMoiPhongTrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTimPhongTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTimPhongTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnlTTPTLayout.setVerticalGroup(
            pnlTTPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTPTLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblDSPT1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTTPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLamMoiPhongTrong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTimPhongTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimPhongTrong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollDSPT, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlChinh.setBackground(new java.awt.Color(102, 204, 255));

        btnThemDichVu.setBackground(new java.awt.Color(204, 255, 204));
        btnThemDichVu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnThemDichVu.setText("THÊM DỊCH VỤ");
        btnThemDichVu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDichVuActionPerformed(evt);
            }
        });

        tblDSPhongDat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã PT", "Tên Phòng", "Tên Khách", "Loại Phòng", "Giá Phòng", "Ngày Nhận Phòng", "Ngày Trả Phòng"
            }
        ));
        scrollDSPDD.setViewportView(tblDSPhongDat);

        lblDSPT2.setBackground(new java.awt.Color(102, 204, 255));
        lblDSPT2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDSPT2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDSPT2.setText("DANH SÁCH PHÒNG ĐANG SỬ DỤNG");

        btnTim.setBackground(new java.awt.Color(204, 255, 255));
        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        txtTim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnLamMoi.setBackground(new java.awt.Color(204, 255, 255));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLamMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        tblDSDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollDSDV.setViewportView(tblDSDV);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH DỊCH VỤ ĐANG SỬ DỤNG");

        javax.swing.GroupLayout pnlChinhLayout = new javax.swing.GroupLayout(pnlChinh);
        pnlChinh.setLayout(pnlChinhLayout);
        pnlChinhLayout.setHorizontalGroup(
            pnlChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChinhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollDSPDD)
                    .addGroup(pnlChinhLayout.createSequentialGroup()
                        .addGroup(pnlChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChinhLayout.createSequentialGroup()
                                .addComponent(btnThemDichVu)
                                .addGap(128, 128, 128)
                                .addComponent(lblDSPT2))
                            .addGroup(pnlChinhLayout.createSequentialGroup()
                                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollDSDV))
                .addContainerGap())
        );
        pnlChinhLayout.setVerticalGroup(
            pnlChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChinhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemDichVu)
                    .addComponent(lblDSPT2))
                .addGap(5, 5, 5)
                .addGroup(pnlChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollDSPDD, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollDSDV, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        pnlBottom.setBackground(new java.awt.Color(102, 204, 255));

        btnDangXuat.setBackground(new java.awt.Color(0, 0, 0));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setText("ĐĂNG XUẤT");
        btnDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnDangXuatActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        lblTenNVLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTenNVLogin.setText("họ tên nhân viên");
        lblTenNVLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTenNVLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTenNVLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBottomLayout.createSequentialGroup()
                        .addComponent(btnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlBottomLayout.createSequentialGroup()
                        .addComponent(lblTenNVLogin)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addComponent(pnlTTPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlChinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(pnlBottom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTTPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlChinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        Menu.setPreferredSize(new java.awt.Dimension(94, 60));

        jMenu1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenu1.setActionCommand("HV HOTEL");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu1.setMinimumSize(new java.awt.Dimension(100, 45));
        jMenu1.setPreferredSize(new java.awt.Dimension(100, 45));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        Menu.add(jMenu1);

        menuPhong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuPhong.setText("   PHÒNG");
        menuPhong.setToolTipText("");
        menuPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuPhong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuPhong.setMinimumSize(new java.awt.Dimension(190, 52));
        menuPhong.setPreferredSize(new java.awt.Dimension(180, 45));
        menuPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPhongActionPerformed(evt);
            }
        });

        Phong.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Phong.setText("PHÒNG");
        Phong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Phong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhongActionPerformed(evt);
            }
        });
        menuPhong.add(Phong);
        menuPhong.add(jSeparator12);

        DatPhong.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        DatPhong.setText("ĐẶT PHÒNG");
        DatPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatPhongActionPerformed(evt);
            }
        });
        menuPhong.add(DatPhong);
        menuPhong.add(jSeparator13);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem3.setText("TRẢ PHÒNG");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuPhong.add(jMenuItem3);
        menuPhong.add(jSeparator1);

        QuanLyPhong.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        QuanLyPhong.setText("QUẢN LÝ PHÒNG");
        QuanLyPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuanLyPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanLyPhongActionPerformed(evt);
            }
        });
        menuPhong.add(QuanLyPhong);
        menuPhong.add(jSeparator2);

        QuanLyLoaiPhong.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        QuanLyLoaiPhong.setText("QUẢN LÝ LOẠI PHÒNG");
        QuanLyLoaiPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuanLyLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanLyLoaiPhongActionPerformed(evt);
            }
        });
        menuPhong.add(QuanLyLoaiPhong);
        menuPhong.add(jSeparator11);

        Menu.add(menuPhong);

        menuDichVu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuDichVu.setText("DỊCH VỤ");
        menuDichVu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuDichVu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuDichVu.setPreferredSize(new java.awt.Dimension(180, 34));
        menuDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDichVuActionPerformed(evt);
            }
        });
        menuDichVu.add(jSeparator3);

        quanlyDV.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanlyDV.setText("QUẢN LÝ DỊCH VỤ");
        quanlyDV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanlyDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanlyDVActionPerformed(evt);
            }
        });
        menuDichVu.add(quanlyDV);
        menuDichVu.add(jSeparator7);
        menuDichVu.add(jSeparator8);

        quanLyLoaiDV.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyLoaiDV.setText("QUẢN LÝ LOẠI DỊCH VỤ");
        quanLyLoaiDV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyLoaiDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyLoaiDVActionPerformed(evt);
            }
        });
        menuDichVu.add(quanLyLoaiDV);
        menuDichVu.add(jSeparator9);

        quanLyDonVi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyDonVi.setText("QUẢN LÝ ĐƠN VỊ");
        quanLyDonVi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyDonVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyDonViActionPerformed(evt);
            }
        });
        menuDichVu.add(quanLyDonVi);

        Menu.add(menuDichVu);

        menuKhachHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuKhachHang.setText("KHÁCH HÀNG");
        menuKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuKhachHang.setPreferredSize(new java.awt.Dimension(205, 34));

        quanLyKH.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyKH.setText("QUẢN LÝ KHÁCH HÀNG");
        quanLyKH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyKHActionPerformed(evt);
            }
        });
        menuKhachHang.add(quanLyKH);

        Menu.add(menuKhachHang);

        menuNhanVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuNhanVien.setText("NHÂN VIÊN");
        menuNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuNhanVien.setMaximumSize(new java.awt.Dimension(185, 32767));
        menuNhanVien.setPreferredSize(new java.awt.Dimension(180, 34));
        menuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhanVienActionPerformed(evt);
            }
        });
        menuNhanVien.add(jSeparator4);

        quanLyNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyNhanVien.setText("QUẢN LÝ NHÂN VIÊN");
        quanLyNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyNhanVienActionPerformed(evt);
            }
        });
        menuNhanVien.add(quanLyNhanVien);

        Menu.add(menuNhanVien);

        menuHoaDon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuHoaDon.setText("  HOÁ ĐƠN");
        menuHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuHoaDon.setPreferredSize(new java.awt.Dimension(180, 34));
        menuHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHoaDonMouseClicked(evt);
            }
        });
        menuHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHoaDonActionPerformed(evt);
            }
        });
        menuHoaDon.add(jSeparator5);

        quanLyHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyHoaDon.setText("QUẢN LÝ HOÁ ĐƠN");
        quanLyHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyHoaDonActionPerformed(evt);
            }
        });
        menuHoaDon.add(quanLyHoaDon);

        Menu.add(menuHoaDon);

        menuThongKe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuThongKe.setText(" THỐNG KÊ");
        menuThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuThongKe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuThongKe.setPreferredSize(new java.awt.Dimension(180, 34));
        menuThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuThongKeMouseClicked(evt);
            }
        });
        menuThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThongKeActionPerformed(evt);
            }
        });

        tkBieuDo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tkBieuDo.setText("BIỂU ĐỒ");
        tkBieuDo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tkBieuDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkBieuDoActionPerformed(evt);
            }
        });
        menuThongKe.add(tkBieuDo);
        menuThongKe.add(jSeparator6);

        Menu.add(menuThongKe);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
        
  	setDefaultCloseOperation(0);      
        
      modelDSPhongDat = new DefaultTableModel(colsDSPhongDat,0);
      tblDSPhongDat = new JTable(modelDSPhongDat);
  	scrollDSPDD.setViewportView(tblDSPhongDat);
  	
      DocDuLieuDatabaseVaoTableDSPhongDat();
      
      ListSelectionModel listSelectionModelDSPhongDat = tblDSPhongDat.getSelectionModel();
      
      listSelectionModelDSPhongDat.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
      
      listSelectionModelDSPhongDat.addListSelectionListener(new ListSelectionListener() {
  	   @Override
  	   public void valueChanged(ListSelectionEvent e) {   
  		   modelDSDV.setRowCount(0);
  		   DocDuLieuDatabaseVaoTableDSDV();
  	   }
    });
      modelDSDV = new DefaultTableModel(colsDSDV,0);
      tblDSDV = new JTable(modelDSDV);
  	scrollDSDV.setViewportView(tblDSDV);
  	
  	 modelDSPT = new DefaultTableModel(colsDSPT,0);
     tblDSPT = new JTable(modelDSPT);
 	scrollDSPT.setViewportView(tblDSPT);
 	
 	DocDuLieuDatabaseVaoDSPhong();
  	
  	hienThiNVDN();
    
      if(quanLy()) {
      	lblTenNVLogin.addMouseListener(new java.awt.event.MouseAdapter() {
              public void mouseClicked(java.awt.event.MouseEvent evt) {
                  lblTenNVLoginMouseClicked(evt);
              }
          });
      }
      else
      	lblTenNVLogin.setEnabled(false);
        
    }// </editor-fold>//GEN-END:initComponents
  
    
// 	setDefaultCloseOperation(0);      
//    
//    modelDSPhongDat = new DefaultTableModel(colsDSPhongDat,0);
//    tblDSPhongDat = new JTable(modelDSPhongDat);
//	scrollDSPDD.setViewportView(tblDSPhongDat);
//	
//    DocDuLieuDatabaseVaoTableDSPhongDat();
//    
//    ListSelectionModel listSelectionModelDSPhongDat = tblDSPhongDat.getSelectionModel();
//    
//    listSelectionModelDSPhongDat.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
//    
//    listSelectionModelDSPhongDat.addListSelectionListener(new ListSelectionListener() {
//	   @Override
//	   public void valueChanged(ListSelectionEvent e) {   
//		   modelDSDV.setRowCount(0);
//		   DocDuLieuDatabaseVaoTableDSDV();
//	   }
//  });
//    modelDSDV = new DefaultTableModel(colsDSDV,0);
//    tblDSDV = new JTable(modelDSDV);
//	scrollDSDV.setViewportView(tblDSDV);
//	
//	 modelDSPT = new DefaultTableModel(colsDSPT,0);
//   tblDSPT = new JTable(modelDSPT);
//	scrollDSPT.setViewportView(tblDSPT);
//	
//	DocDuLieuDatabaseVaoDSPhong();
//	
//	hienThiNVDN();
//    
//    if(quanLy()) {
//    	lblTenNVLogin.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                lblTenNVLoginMouseClicked(evt);
//            }
//        });
//    }
//    else
//    	lblTenNVLogin.setEnabled(false);

    
    public void hienThiNVDN() {
    	NhanVien nv = DAO_NhanVien.getNhanVienDangLogin();
		lblTenNVLogin.setText(getTenChucVu(nv.getChucVu().getMaCV())+" - " + nv.getTenNV());
    }
    public boolean quanLy() {
    	NhanVien nv = DAO_NhanVien.getNhanVienDangLogin();
    	if((nv.getChucVu().getMaCV()).equalsIgnoreCase("CV001")==true)
    		return true;
    	return false;
    }
    
    public String getTenChucVu(String maCV) {
    	ArrayList<ChucVu> lstChucVu = DAO_ChucVu.getAllChucVu();
    	for (ChucVu cv : lstChucVu) {
    		if(cv.getMaCV().equalsIgnoreCase(maCV))
    			return cv.getTenCV();
    	}
    	return "";
    }
    
    private void lblTenNVLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTenNVLoginMouseClicked
        // TODO add your handling code here:
        GD_ThongTinNhanVien uiTTNV = new GD_ThongTinNhanVien();
        //    	this.setVisible(false);
        uiTTNV.setVisible(true);
    }//GEN-LAST:event_lblTenNVLoginMouseClicked

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
    	int result = JOptionPane.showConfirmDialog(rootPane,
                "Bạn có chắc muốn đăng xuất!",
                "XÁC NHẬN",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
        	GD_DangNhap uiLogout = new GD_DangNhap();
//        	GD_DaiSanh uiDaiSanh = new GD_DaiSanh();
            ArrayList<NhanVien> listNV = DAO_NhanVien.getAllNhanVien();
            for (NhanVien nv : listNV) {
    			if(nv.isTinhTrang()==true)
    				DAO_NhanVien.capNhatTinhTrangNVDX(nv);
    	        this.setVisible(false);
    	        uiLogout.setVisible(true);
    		}
            JOptionPane.showMessageDialog(rootPane, "Bạn đã đăng xuất!!!");
        } else if (result == JOptionPane.NO_OPTION) {
        	JOptionPane.showMessageDialog(rootPane, "Đăng xuất thất bại!!");
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed

    public void timPT(String ten) {
		ArrayList<PhieuThue> list = DAO_PhieuThue.timPT(ten);
		if(list.size()==0) {
			JOptionPane.showMessageDialog(rootPane, "Không tìm thấy phòng này!", "Lỗi!", JOptionPane.WARNING_MESSAGE);
			return;
		}
		for (PhieuThue hdp : list) {
			modelDSPhongDat.addRow(new Object[] {
					hdp.getMaPT(),
					getTenKH(hdp.getHoaDon().getKhachHang().getMaKH()),
					getTenPhong(hdp.getPhong().getMaPhong()),
					getTenLP(hdp.getPhong().getLoaiPhong().getMaLP()),
					getGiaLP(hdp.getPhong().getLoaiPhong().getMaLP()),
					new SimpleDateFormat("dd-MM-yyyy").format(new Date(hdp.getNgayDatPhong().getTime())),
					new SimpleDateFormat("dd-MM-yyyy").format(new Date(hdp.getNgayTraPhong().getTime())),
			});}
    }
    
    private void btnThemDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDichVuActionPerformed
        // TODO add your handling code here:
        GD_DatDichVu uiThemDV = new GD_DatDichVu();
//        this.setVisible(false);
        uiThemDV.setVisible(true);
    }//GEN-LAST:event_btnThemDichVuActionPerformed

    public void setGiaTriMacDinhPhongTrong() {
    	modelDSPT.setRowCount(0);
    	DocDuLieuDatabaseVaoDSPhong();
    	txtTimPhongTrong.setText("");
    	txtTimPhongTrong.requestFocus();
    }
    
    public void setGiaTriMacDinhPhieuThue() {
    	modelDSPhongDat.setRowCount(0);
    	modelDSDV.setRowCount(0);
    	DocDuLieuDatabaseVaoTableDSPhongDat();
    	DocDuLieuDatabaseVaoTableDSDV();
    	txtTimPhongTrong.setText("");
    }
    
    public void timPhongTrong(String ten) {
		ArrayList<Phong> list = DAO_Phong.timPhongTrongDSP(ten);
		if(list.size()==0) {
			JOptionPane.showMessageDialog(rootPane, "Không tìm thấy phòng trống này!", "Lỗi!", JOptionPane.WARNING_MESSAGE);
			return;
		}
		for (Phong p : list) {
			modelDSPT.addRow(new Object[] {
					p.getTenPhong(),
					getTenLP(p.getLoaiPhong().getMaLP()),
					getGiaLP(p.getLoaiPhong().getMaLP()),
			});}
    }
    
    
    private void btnTimPhongTrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimPhongTrongActionPerformed
        // TODO add your handling code here:
        String ten = txtTimPhongTrong.getText().replaceAll("\\s\\s+", " ").trim();
        modelDSPT.setRowCount(0);
        timPhongTrong(ten);
    }//GEN-LAST:event_btnTimPhongTrongActionPerformed

    private void btnLamMoiPhongTrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiPhongTrongActionPerformed
        // TODO add your handling code here:
    	setGiaTriMacDinhPhongTrong();
    }//GEN-LAST:event_btnLamMoiPhongTrongActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        GD_DaiSanh uiSanh = new GD_DaiSanh();
        this.setVisible(false);
        uiSanh.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    	GD_DaiSanh uiMain = new GD_DaiSanh();
        this.setVisible(false);
        uiMain.setVisible(true);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void PhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhongActionPerformed
        // TODO add your handling code here:
        GD_Chinh ui = new GD_Chinh();
        this.setVisible(false);
        ui.setVisible(true);
    }//GEN-LAST:event_PhongActionPerformed

    private void DatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatPhongActionPerformed
        // TODO add your handling code here:
        GD_DatPhong uiDatPhong = new GD_DatPhong();

        uiDatPhong.setVisible(true);
    }//GEN-LAST:event_DatPhongActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        GD_TraPhong uiTraPhong = new GD_TraPhong();

        uiTraPhong.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void QuanLyPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanLyPhongActionPerformed
        // TODO add your handling code here:
        GD_QuanLyPhong uiQLP = new  GD_QuanLyPhong();
        this.setVisible(false);
        uiQLP.setVisible(true);
    }//GEN-LAST:event_QuanLyPhongActionPerformed

    private void QuanLyLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanLyLoaiPhongActionPerformed
        // TODO add your handling code here:
        GD_QuanLyLoaiPhong uiQLLoaiPhong = new GD_QuanLyLoaiPhong();
        this.setVisible(false);
        uiQLLoaiPhong.setVisible(true);
    }//GEN-LAST:event_QuanLyLoaiPhongActionPerformed

    private void menuPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPhongActionPerformed

    private void quanlyDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanlyDVActionPerformed
        // TODO add your handling code here:
        GD_QuanLyDichVu uiDV = new GD_QuanLyDichVu();
        this.setVisible(false);
        uiDV.setVisible(true);
    }//GEN-LAST:event_quanlyDVActionPerformed

    private void quanLyLoaiDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyLoaiDVActionPerformed
        // TODO add your handling code here:
        GD_QuanLyLoaiDichVu uiLoaiDV = new GD_QuanLyLoaiDichVu();
        this.setVisible(false);
        uiLoaiDV.setVisible(true);
    }//GEN-LAST:event_quanLyLoaiDVActionPerformed

    private void quanLyDonViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyDonViActionPerformed
        // TODO add your handling code here:
        GD_QuanLyDonVi uiDonVi = new GD_QuanLyDonVi();
        this.setVisible(false);
        uiDonVi.setVisible(true);
    }//GEN-LAST:event_quanLyDonViActionPerformed

    private void menuDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDichVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDichVuActionPerformed

    private void quanLyKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyKHActionPerformed
        GD_QuanLyKhachHang uiKH = new GD_QuanLyKhachHang();
        this.setVisible(false);
        uiKH.setVisible(true);
    }//GEN-LAST:event_quanLyKHActionPerformed

    private void quanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyNhanVienActionPerformed
        // TODO add your handling code here:
        GD_QuanLyNhanVien uiQLNV = new GD_QuanLyNhanVien();
        this.setVisible(false);
        uiQLNV.setVisible(true);
    }//GEN-LAST:event_quanLyNhanVienActionPerformed

    private void menuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuNhanVienActionPerformed

    private void quanLyHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyHoaDonActionPerformed
        GD_QuanLyHoaDon uiHD = new GD_QuanLyHoaDon();
        this.setVisible(false);
        uiHD.setVisible(true);
    }//GEN-LAST:event_quanLyHoaDonActionPerformed

    private void menuHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHoaDonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHoaDonMouseClicked

    private void menuHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHoaDonActionPerformed

    private void tkBieuDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkBieuDoActionPerformed
        // TODO add your handling code here:
        GD_ThongKeBieuDo uiTK = new GD_ThongKeBieuDo();
        this.setVisible(false);
        uiTK.setVisible(true);
    }//GEN-LAST:event_tkBieuDoActionPerformed

    private void menuThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuThongKeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuThongKeMouseClicked

    private void menuThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThongKeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuThongKeActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
    	String ten = txtTim.getText().replaceAll("\\s\\s+", " ").trim();
        modelDSPhongDat.setRowCount(0);
        timPT(ten);
    	
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
    	setGiaTriMacDinhPhieuThue();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void txtTimPhongTrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimPhongTrongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimPhongTrongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_Chinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_Chinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DatPhong;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem Phong;
    private javax.swing.JMenuItem QuanLyLoaiPhong;
    private javax.swing.JMenuItem QuanLyPhong;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLamMoiPhongTrong;
    private javax.swing.JButton btnThemDichVu;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnTimPhongTrong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JLabel lblDSPT1;
    private javax.swing.JLabel lblDSPT2;
    private javax.swing.JLabel lblTenNVLogin;
    private javax.swing.JMenu menuDichVu;
    private javax.swing.JMenu menuHoaDon;
    private javax.swing.JMenu menuKhachHang;
    private javax.swing.JMenu menuNhanVien;
    private javax.swing.JMenu menuPhong;
    private javax.swing.JMenu menuThongKe;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlChinh;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlTTPT;
    private javax.swing.JMenuItem quanLyDonVi;
    private javax.swing.JMenuItem quanLyHoaDon;
    private javax.swing.JMenuItem quanLyKH;
    private javax.swing.JMenuItem quanLyLoaiDV;
    private javax.swing.JMenuItem quanLyNhanVien;
    private javax.swing.JMenuItem quanlyDV;
    private javax.swing.JScrollPane scrollDSDV;
    private javax.swing.JScrollPane scrollDSPDD;
    private javax.swing.JScrollPane scrollDSPT;
    private javax.swing.JTable tblDSDV;
    private javax.swing.JTable tblDSPT;
    private javax.swing.JTable tblDSPhongDat;
    private javax.swing.JMenuItem tkBieuDo;
    private javax.swing.JTextField txtTim;
    private javax.swing.JTextField txtTimPhongTrong;
    // End of variables declaration//GEN-END:variables
}
