/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import dao.DAO_ChucVu;
import dao.DAO_NhanVien;
import entity.ChucVu;
import entity.NhanVien;

/**
 *
 * @author admin
 */
public class GD_DaiSanh extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form GD_DaiSanh
     */
    public GD_DaiSanh() {
        
        initComponents();
        setExtendedState(GD_DaiSanh.MAXIMIZED_BOTH);
    }
    ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource(".//images//logo.PNG"));
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlBottom = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();
        lblTenNVLogin = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuPhong = new javax.swing.JMenu();
        Phong = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        DatPhong = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        QuanLyPhong = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        QuanLyLoaiPhong = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        menuDichVu = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        quanlyDV = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        quanLyLoaiDV = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        quanLyDonVi = new javax.swing.JMenuItem();
        menuKhachHang = new javax.swing.JMenu();
        quanLyKH = new javax.swing.JMenuItem();
        menuNhanVien = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        quanLyNhanVien = new javax.swing.JMenuItem();
        menuHoaDon = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        quanLyHoaDon = new javax.swing.JMenuItem();
        menuThongKe = new javax.swing.JMenu();
        tkBieuDo = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\hotels\\src\\main\\resources\\images\\main-screen.jpg")); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1340, 576));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1533, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlBottom.setBackground(new java.awt.Color(102, 204, 255));

        btnDangXuat.setBackground(new java.awt.Color(0, 0, 0));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setText("ĐĂNG XUẤT");
        btnDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        lblTenNVLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTenNVLogin.setText("họ tên nhân viên");
        lblTenNVLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTenNVLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTenNVLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTenNVLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenNVLogin))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        Menu.setPreferredSize(new java.awt.Dimension(94, 60));

        jMenu1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\logo.png")); // NOI18N
        jMenu1.setActionCommand("HV HOTEL");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu1.setMinimumSize(new java.awt.Dimension(100, 45));
        jMenu1.setPreferredSize(new java.awt.Dimension(100, 45));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        Menu.add(jMenu1);

        menuPhong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuPhong.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_room.png")); // NOI18N
        menuPhong.setText("   PHÒNG");
        menuPhong.setToolTipText("");
        menuPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuPhong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuPhong.setMinimumSize(new java.awt.Dimension(190, 52));
        menuPhong.setPreferredSize(new java.awt.Dimension(180, 45));
        menuPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPhongActionPerformed(evt);
            }
        });

        Phong.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Phong.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_phong.png")); // NOI18N
        Phong.setText("PHÒNG");
        Phong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Phong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhongActionPerformed(evt);
            }
        });
        menuPhong.add(Phong);
        menuPhong.add(jSeparator10);
        menuPhong.add(jSeparator12);

        DatPhong.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        DatPhong.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_datPhong.png")); // NOI18N
        DatPhong.setText("ĐẶT PHÒNG");
        DatPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatPhongActionPerformed(evt);
            }
        });
        menuPhong.add(DatPhong);
        menuPhong.add(jSeparator13);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_checkout (1).png")); // NOI18N
        jMenuItem3.setText("TRẢ PHÒNG");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuPhong.add(jMenuItem3);
        menuPhong.add(jSeparator1);

        QuanLyPhong.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        QuanLyPhong.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_phong.png")); // NOI18N
        QuanLyPhong.setText("QUẢN LÝ PHÒNG");
        QuanLyPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuanLyPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanLyPhongActionPerformed(evt);
            }
        });
        menuPhong.add(QuanLyPhong);
        menuPhong.add(jSeparator2);

        QuanLyLoaiPhong.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        QuanLyLoaiPhong.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_phong.png")); // NOI18N
        QuanLyLoaiPhong.setText("QUẢN LÝ LOẠI PHÒNG");
        QuanLyLoaiPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuanLyLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanLyLoaiPhongActionPerformed(evt);
            }
        });
        menuPhong.add(QuanLyLoaiPhong);
        menuPhong.add(jSeparator11);

        Menu.add(menuPhong);

        menuDichVu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuDichVu.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_service.png")); // NOI18N
        menuDichVu.setText("DỊCH VỤ");
        menuDichVu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuDichVu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuDichVu.setPreferredSize(new java.awt.Dimension(180, 34));
        menuDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDichVuActionPerformed(evt);
            }
        });
        menuDichVu.add(jSeparator3);

        quanlyDV.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanlyDV.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_list.png")); // NOI18N
        quanlyDV.setText("QUẢN LÝ DỊCH VỤ");
        quanlyDV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanlyDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanlyDVActionPerformed(evt);
            }
        });
        menuDichVu.add(quanlyDV);
        menuDichVu.add(jSeparator7);
        menuDichVu.add(jSeparator8);

        quanLyLoaiDV.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyLoaiDV.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_list.png")); // NOI18N
        quanLyLoaiDV.setText("QUẢN LÝ LOẠI DỊCH VỤ");
        quanLyLoaiDV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyLoaiDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyLoaiDVActionPerformed(evt);
            }
        });
        menuDichVu.add(quanLyLoaiDV);
        menuDichVu.add(jSeparator9);

        quanLyDonVi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyDonVi.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_list.png")); // NOI18N
        quanLyDonVi.setText("QUẢN LÝ ĐƠN VỊ");
        quanLyDonVi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyDonVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyDonViActionPerformed(evt);
            }
        });
        menuDichVu.add(quanLyDonVi);

        Menu.add(menuDichVu);

        menuKhachHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuKhachHang.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_customer.png")); // NOI18N
        menuKhachHang.setText("KHÁCH HÀNG");
        menuKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuKhachHang.setPreferredSize(new java.awt.Dimension(205, 34));

        quanLyKH.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyKH.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_list.png")); // NOI18N
        quanLyKH.setText("QUẢN LÝ KHÁCH HÀNG");
        quanLyKH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyKHActionPerformed(evt);
            }
        });
        menuKhachHang.add(quanLyKH);

        Menu.add(menuKhachHang);

        menuNhanVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuNhanVien.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_employee.png")); // NOI18N
        menuNhanVien.setText("NHÂN VIÊN");
        menuNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuNhanVien.setMaximumSize(new java.awt.Dimension(185, 32767));
        menuNhanVien.setPreferredSize(new java.awt.Dimension(180, 34));
        menuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhanVienActionPerformed(evt);
            }
        });
        menuNhanVien.add(jSeparator4);

        quanLyNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyNhanVien.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_list.png")); // NOI18N
        quanLyNhanVien.setText("QUẢN LÝ NHÂN VIÊN");
        quanLyNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyNhanVienActionPerformed(evt);
            }
        });
        menuNhanVien.add(quanLyNhanVien);

        Menu.add(menuNhanVien);

        menuHoaDon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuHoaDon.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_oder.png")); // NOI18N
        menuHoaDon.setText("  HOÁ ĐƠN");
        menuHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuHoaDon.setPreferredSize(new java.awt.Dimension(180, 34));
        menuHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHoaDonMouseClicked(evt);
            }
        });
        menuHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHoaDonActionPerformed(evt);
            }
        });
        menuHoaDon.add(jSeparator5);

        quanLyHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyHoaDon.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_list.png")); // NOI18N
        quanLyHoaDon.setText("QUẢN LÝ HOÁ ĐƠN");
        quanLyHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyHoaDonActionPerformed(evt);
            }
        });
        menuHoaDon.add(quanLyHoaDon);

        Menu.add(menuHoaDon);

        menuThongKe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuThongKe.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_chart_1.png")); // NOI18N
        menuThongKe.setText(" THỐNG KÊ");
        menuThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuThongKe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuThongKe.setPreferredSize(new java.awt.Dimension(180, 34));
        menuThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuThongKeMouseClicked(evt);
            }
        });
        menuThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThongKeActionPerformed(evt);
            }
        });

        tkBieuDo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tkBieuDo.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_chart.png")); // NOI18N
        tkBieuDo.setText("BIỂU ĐỒ");
        tkBieuDo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tkBieuDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkBieuDoActionPerformed(evt);
            }
        });
        menuThongKe.add(tkBieuDo);
        menuThongKe.add(jSeparator6);

        Menu.add(menuThongKe);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
//	hienThiNVDN();
//  
//  if(quanLy()) {
//  	lblTenNVLogin.addMouseListener(new java.awt.event.MouseAdapter() {
//          public void mouseClicked(java.awt.event.MouseEvent evt) {
//              lblTenNVLoginMouseClicked(evt);
//          }
//      });
//  }
//  else
//  	lblTenNVLogin.setEnabled(false);

    
    
    
    public void hienThiNVDN() {
    	NhanVien nv = DAO_NhanVien.getNhanVienDangLogin();
		lblTenNVLogin.setText(getTenChucVu(nv.getChucVu().getMaCV())+" - " + nv.getTenNV());
    }
    public boolean quanLy() {
    	NhanVien nv = DAO_NhanVien.getNhanVienDangLogin();
    	if((nv.getChucVu().getMaCV()).equalsIgnoreCase("CV001")==true)
    		return true;
    	return false;
    }
    
    public String getTenChucVu(String maCV) {
    	ArrayList<ChucVu> lstChucVu = DAO_ChucVu.getAllChucVu();
    	for (ChucVu cv : lstChucVu) {
    		if(cv.getMaCV().equalsIgnoreCase(maCV))
    			return cv.getTenCV();
    	}
    	return "";
    }
    
    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(rootPane,
            "Bạn có chắc muốn đăng xuất!",
            "XÁC NHẬN",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            GD_DangNhap uiLogout = new GD_DangNhap();
//            GD_DaiSanh uiDaiSanh = new GD_DaiSanh();
            ArrayList<NhanVien> listNV = DAO_NhanVien.getAllNhanVien();
            for (NhanVien nv : listNV) {
                if(nv.isTinhTrang()==true)
					try {
						DAO_NhanVien.capNhatTinhTrangNVDX(nv);
					} catch (Exception e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
                this.setVisible(false);
                uiLogout.setVisible(true);
            }
            JOptionPane.showMessageDialog(rootPane, "Bạn đã đăng xuất!!!");
        } else if (result == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(rootPane, "Đăng xuất thất bại!!");
        }
        

    }//GEN-LAST:event_btnDangXuatActionPerformed
    
    

    private void lblTenNVLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTenNVLoginMouseClicked
        // TODO add your handling code here:
        GD_ThongTinNhanVien uiTTNV = new GD_ThongTinNhanVien();
        //    	this.setVisible(false);
        uiTTNV.setVisible(true);
    }//GEN-LAST:event_lblTenNVLoginMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        GD_DaiSanh uiSanh = new GD_DaiSanh();
        this.setVisible(false);
        uiSanh.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        GD_DaiSanh uiMain = new GD_DaiSanh();
        this.setVisible(false);
        uiMain.setVisible(true);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void PhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhongActionPerformed
        // TODO add your handling code here:
        GD_Chinh ui = new GD_Chinh();
        this.setVisible(false);
        ui.setVisible(true);
    }//GEN-LAST:event_PhongActionPerformed

    private void DatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatPhongActionPerformed
        // TODO add your handling code here:
        GD_DatPhong uiDatPhong = new GD_DatPhong();

        uiDatPhong.setVisible(true);
    }//GEN-LAST:event_DatPhongActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        GD_TraPhong uiTraPhong = new GD_TraPhong();

        uiTraPhong.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void QuanLyPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanLyPhongActionPerformed
        // TODO add your handling code here:
        GD_QuanLyPhong uiQLP = new  GD_QuanLyPhong();
        this.setVisible(false);
        uiQLP.setVisible(true);
    }//GEN-LAST:event_QuanLyPhongActionPerformed

    private void QuanLyLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanLyLoaiPhongActionPerformed
        // TODO add your handling code here:
        GD_QuanLyLoaiPhong uiQLLoaiPhong = new GD_QuanLyLoaiPhong();
        this.setVisible(false);
        uiQLLoaiPhong.setVisible(true);
    }//GEN-LAST:event_QuanLyLoaiPhongActionPerformed

    private void menuPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPhongActionPerformed

    private void quanlyDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanlyDVActionPerformed
        // TODO add your handling code here:
        GD_QuanLyDichVu uiDV = new GD_QuanLyDichVu();
        this.setVisible(false);
        uiDV.setVisible(true);
    }//GEN-LAST:event_quanlyDVActionPerformed

    private void quanLyLoaiDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyLoaiDVActionPerformed
        // TODO add your handling code here:
        GD_QuanLyLoaiDichVu uiLoaiDV = new GD_QuanLyLoaiDichVu();
        this.setVisible(false);
        uiLoaiDV.setVisible(true);
    }//GEN-LAST:event_quanLyLoaiDVActionPerformed

    private void quanLyDonViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyDonViActionPerformed
        // TODO add your handling code here:
        GD_QuanLyDonVi uiDonVi = new GD_QuanLyDonVi();
        this.setVisible(false);
        uiDonVi.setVisible(true);
    }//GEN-LAST:event_quanLyDonViActionPerformed

    private void menuDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDichVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDichVuActionPerformed

    private void quanLyKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyKHActionPerformed
        GD_QuanLyKhachHang uiKH = new GD_QuanLyKhachHang();
        this.setVisible(false);
        uiKH.setVisible(true);
    }//GEN-LAST:event_quanLyKHActionPerformed

    private void quanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyNhanVienActionPerformed
        // TODO add your handling code here:
        GD_QuanLyNhanVien uiQLNV = new GD_QuanLyNhanVien();
        this.setVisible(false);
        uiQLNV.setVisible(true);
    }//GEN-LAST:event_quanLyNhanVienActionPerformed

    private void menuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuNhanVienActionPerformed

    private void quanLyHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyHoaDonActionPerformed
        GD_QuanLyHoaDon uiHD = new GD_QuanLyHoaDon();
        this.setVisible(false);
        uiHD.setVisible(true);
    }//GEN-LAST:event_quanLyHoaDonActionPerformed

    private void menuHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHoaDonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHoaDonMouseClicked

    private void menuHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHoaDonActionPerformed

    private void tkBieuDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkBieuDoActionPerformed
        // TODO add your handling code here:
        GD_ThongKeBieuDo uiTK = new GD_ThongKeBieuDo();
        this.setVisible(false);
        uiTK.setVisible(true);
    }//GEN-LAST:event_tkBieuDoActionPerformed

    private void menuThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuThongKeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuThongKeMouseClicked

    private void menuThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThongKeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_DaiSanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_DaiSanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_DaiSanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_DaiSanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_DaiSanh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DatPhong;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem Phong;
    private javax.swing.JMenuItem QuanLyLoaiPhong;
    private javax.swing.JMenuItem QuanLyPhong;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JLabel lblTenNVLogin;
    private javax.swing.JMenu menuDichVu;
    private javax.swing.JMenu menuHoaDon;
    private javax.swing.JMenu menuKhachHang;
    private javax.swing.JMenu menuNhanVien;
    private javax.swing.JMenu menuPhong;
    private javax.swing.JMenu menuThongKe;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JMenuItem quanLyDonVi;
    private javax.swing.JMenuItem quanLyHoaDon;
    private javax.swing.JMenuItem quanLyKH;
    private javax.swing.JMenuItem quanLyLoaiDV;
    private javax.swing.JMenuItem quanLyNhanVien;
    private javax.swing.JMenuItem quanlyDV;
    private javax.swing.JMenuItem tkBieuDo;
    // End of variables declaration//GEN-END:variables
}
