/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package ui;


import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import connectDB.Database;
import dao.DAO_HoaDon;
import dao.DAO_KhachHang;
import dao.DAO_LoaiPhong;
import dao.DAO_PhieuThue;
import dao.DAO_Phong;
import entity.HoaDon;
import entity.KhachHang;
import entity.LoaiPhong;
import entity.PhieuThue;
import entity.Phong;

import java.sql.*;

/**
 *
 * @author admin
 */
public class GD_DatPhong extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** Creates new form GD_DatPhong */
    public GD_DatPhong() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    private DefaultTableModel modelDSKH;
    private String[] cols={"Mã KH","Tên KH","Số CMND", "Số ĐT"};
    
    public void DocDuLieuDatabaseVaoTableDSKH() {
		ArrayList<KhachHang> list = DAO_KhachHang.getAllKhachHang();
		modelDSKH.setRowCount(0);
		for (KhachHang kh : list) {
			modelDSKH.addRow(new Object[] {
					kh.getMaKH(),kh.getTenKH(),
					kh.getSoCMND(),kh.getSoDT()});}
    }
    
    
    
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel2 = new javax.swing.JPanel();
        lblTTKH = new javax.swing.JLabel();
        lblDSKH = new javax.swing.JPanel();
        crollDSKH = new javax.swing.JScrollPane();
        tblDSKH = new javax.swing.JTable();
        lblTieuDeDSKH = new javax.swing.JLabel();
        btnLamMoi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        pnlDatPhong = new javax.swing.JPanel();
        lblDatPhong = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxLoaiPhong = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        cbxTenPhong = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtGiaPhong = new javax.swing.JTextField();
        btnDatPhong = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        txtTenKH = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTienCoc = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        ngayDatPhong = new com.toedter.calendar.JDateChooser();
        ngayTraPhong = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        lblTTKH.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTTKH.setText("ĐẶT PHÒNG");

        lblDSKH.setBackground(new java.awt.Color(153, 255, 255));

        tblDSKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Khách", "Tên Khách", "CMND/PASSPORT", "Số Điện Thoại"
            }
        ));
        crollDSKH.setViewportView(tblDSKH);

        lblTieuDeDSKH.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTieuDeDSKH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTieuDeDSKH.setText("DANH SÁCH KHÁCH HÀNG");

        btnLamMoi.setBackground(new java.awt.Color(204, 255, 255));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon("C:\\hotels (4)\\hotels\\src\\main\\java\\images\\ic_refresh.png")); // NOI18N
        btnLamMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(204, 255, 204));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setText("THÊM MỚI");
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        txtTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimActionPerformed(evt);
            }
        });

        btnTim.setBackground(new java.awt.Color(102, 204, 255));
        btnTim.setIcon(new javax.swing.ImageIcon("C:\\hotels (4)\\hotels\\src\\main\\java\\images\\ic_search.png")); // NOI18N
        btnTim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lblDSKHLayout = new javax.swing.GroupLayout(lblDSKH);
        lblDSKH.setLayout(lblDSKHLayout);
        lblDSKHLayout.setHorizontalGroup(
            lblDSKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblDSKHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblDSKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTieuDeDSKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(crollDSKH, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lblDSKHLayout.createSequentialGroup()
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        lblDSKHLayout.setVerticalGroup(
            lblDSKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblDSKHLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblTieuDeDSKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblDSKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(lblDSKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTim)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crollDSKH, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlDatPhong.setBackground(new java.awt.Color(153, 255, 255));

        lblDatPhong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDatPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatPhong.setText("THÔNG TIN PHÒNG");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Mã Hóa Đơn");

        txtMaHD.setEditable(false);
        txtMaHD.setBackground(new java.awt.Color(204, 204, 204));
        txtMaHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("CMND");

        txtCMND.setEditable(false);
        txtCMND.setBackground(new java.awt.Color(204, 204, 204));
        txtCMND.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Số Điện Thoại");

        txtSDT.setEditable(false);
        txtSDT.setBackground(new java.awt.Color(204, 204, 204));
        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Ngày Nhận Phòng");

        txtMaKH.setEditable(false);
        txtMaKH.setBackground(new java.awt.Color(204, 204, 204));
        txtMaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaKHActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Mã Khách Hàng");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Loại Phòng");

        cbxLoaiPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxLoaiPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        cbxLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLoaiPhongActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Phòng");

        cbxTenPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxTenPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "102", "103", " " }));
        cbxTenPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTenPhongActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Giá Phòng");

        txtGiaPhong.setEditable(false);
        txtGiaPhong.setBackground(new java.awt.Color(204, 204, 204));
        txtGiaPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnDatPhong.setBackground(new java.awt.Color(102, 204, 255));
        btnDatPhong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDatPhong.setIcon(new javax.swing.ImageIcon("C:\\hotels (4)\\hotels\\src\\main\\java\\images\\Phone_icon (1).png")); // NOI18N
        btnDatPhong.setText("ĐẶT PHÒNG");
        btnDatPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnDatPhongActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        btnRefresh.setBackground(new java.awt.Color(102, 204, 255));
        btnRefresh.setIcon(new javax.swing.ImageIcon("C:\\hotels (4)\\hotels\\src\\main\\java\\images\\ic_refresh.png")); // NOI18N
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        txtTenKH.setEditable(false);
        txtTenKH.setBackground(new java.awt.Color(204, 204, 204));
        txtTenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Tên Khách Hàng");

        txtTienCoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienCocActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Tiền Cọc(Nếu có)");

        ngayDatPhong.setForeground(new java.awt.Color(0, 204, 51));
        ngayDatPhong.setDateFormatString("dd-MM-yyyy");
        ngayDatPhong.setEnabled(false);
        ngayDatPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ngayDatPhong.setMaxSelectableDate(new java.util.Date(253370743300000L));

        ngayTraPhong.setForeground(new java.awt.Color(255, 0, 0));
        ngayTraPhong.setDateFormatString("dd-MM-yyyy");
        ngayTraPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Ngày Trả Phòng");

        javax.swing.GroupLayout pnlDatPhongLayout = new javax.swing.GroupLayout(pnlDatPhong);
        pnlDatPhong.setLayout(pnlDatPhongLayout);
        pnlDatPhongLayout.setHorizontalGroup(
            pnlDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatPhongLayout.createSequentialGroup()
                .addGroup(pnlDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDatPhongLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(pnlDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSDT)
                            .addComponent(txtTienCoc)
                            .addComponent(txtCMND)
                            .addComponent(txtMaKH)
                            .addGroup(pnlDatPhongLayout.createSequentialGroup()
                                .addGroup(pnlDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel19)
                                    .addComponent(txtMaHD, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txtTenKH))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(38, 38, 38)
                        .addGroup(pnlDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ngayTraPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ngayDatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxLoaiPhong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxTenPhong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtGiaPhong)
                                .addComponent(btnDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)
                                .addComponent(jLabel14)
                                .addComponent(jLabel9)
                                .addComponent(jLabel20))
                            .addComponent(jLabel12)))
                    .addGroup(pnlDatPhongLayout.createSequentialGroup()
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDatPhong)
                        .addGap(62, 62, 62)))
                .addGap(23, 23, 23))
        );
        pnlDatPhongLayout.setVerticalGroup(
            pnlDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlDatPhongLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatPhongLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ngayDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngayTraPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlDatPhongLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDatPhongLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxLoaiPhong)))
                .addGap(18, 18, 18)
                .addGroup(pnlDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel14))
                .addGap(7, 7, 7)
                .addGroup(pnlDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTienCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDSKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTTKH)
                        .addGap(298, 298, 298)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTTKH)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDSKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
        
        setGiaTriMacDinhDatPhong();
        // ModelDSKH
        modelDSKH = new DefaultTableModel(cols,0);
        tblDSKH = new JTable(modelDSKH);
        crollDSKH.setViewportView(tblDSKH);
        
      //  tblDSKH.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblDSKH.getColumnModel().getColumn(0);
        tblDSKH.getColumnModel().getColumn(1);
        tblDSKH.getColumnModel().getColumn(2);
        tblDSKH.getColumnModel().getColumn(3);


        // Sự kiện click trên tblDSKH
        ListSelectionModel listSelectionModelDSKH = tblDSKH.getSelectionModel();
        // Thiết lập chỉ click được 1 dòng
        listSelectionModelDSKH.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        // Xử lý sự kiện click
        listSelectionModelDSKH.addListSelectionListener(new ListSelectionListener() {
      		
      		@Override
      		public void valueChanged(ListSelectionEvent e) {
      			// TODO Auto-generated method stub
      			hienThiChiTietKH();
      		}
      	});
        loadCBXLoaiPhong();
        setGiaTriMacDinh();
      //  setResizable(false);
      //  setDefaultCloseOperation(0);
        DocDuLieuDatabaseVaoTableDSKH();
        
        
    }// </editor-fold>//GEN-END:initComponents

//    setGiaTriMacDinhDatPhong();
//  // ModelDSKH
//  modelDSKH = new DefaultTableModel(cols,0);
//  tblDSKH = new JTable(modelDSKH);
//  crollDSKH.setViewportView(tblDSKH);
//  
////  tblDSKH.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
//  tblDSKH.getColumnModel().getColumn(0);
//  tblDSKH.getColumnModel().getColumn(1);
//  tblDSKH.getColumnModel().getColumn(2);
//  tblDSKH.getColumnModel().getColumn(3);
//
//
//  // Sự kiện click trên tblDSKH
//  ListSelectionModel listSelectionModelDSKH = tblDSKH.getSelectionModel();
//  // Thiết lập chỉ click được 1 dòng
//  listSelectionModelDSKH.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
//  // Xử lý sự kiện click
//  listSelectionModelDSKH.addListSelectionListener(new ListSelectionListener() {
//		
//		@Override
//		public void valueChanged(ListSelectionEvent e) {
//			// TODO Auto-generated method stub
//			hienThiChiTietKH();
//		}
//	});
//  loadCBXLoaiPhong();
//  setGiaTriMacDinh();
////  setResizable(false);
////  setDefaultCloseOperation(0);
//  DocDuLieuDatabaseVaoTableDSKH();
  
    
    
    private void txtTienCocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienCocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienCocActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
    	setGiaTriMacDinhDatPhong();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDatPhongActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnDatPhongActionPerformed
        // TODO add your handling code here:
        DatPhong();
        setGiaTriMacDinh();
    }//GEN-LAST:event_btnDatPhongActionPerformed

    private void cbxTenPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTenPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTenPhongActionPerformed

    private void cbxLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLoaiPhongActionPerformed
        // TODO add your handling code here:
        loadCBXSoPhong();
    }//GEN-LAST:event_cbxLoaiPhongActionPerformed

    private void txtMaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaKHActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        String ten = txtTim.getText().replaceAll("\\s\\s+", " ").trim();
        timKH(ten);
    }//GEN-LAST:event_btnTimActionPerformed

    private void txtTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        GD_ThemMoiKhachHang themMoiKH = new GD_ThemMoiKhachHang();
        themMoiKH.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        taiLaiDSKH();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
//        GD_Chinh ui = new GD_Chinh();
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    public void hienThiChiTietKH() {
    	int i = tblDSKH.getSelectedRow();
		
		if(i!=-1) {
			txtMaKH.setText(String.valueOf(tblDSKH.getValueAt(i, 0)));
			txtTenKH.setText(String.valueOf(tblDSKH.getValueAt(i, 1)));
			txtCMND.setText(String.valueOf(tblDSKH.getValueAt(i, 2)));
			txtSDT.setText(String.valueOf(tblDSKH.getValueAt(i, 3)));
//			jDateChooser1.setDate(new SimpleDateFormat("dd-MM-yyyy").parse(String.valueOf()));
		}
    }
    
    public void setGiaTriMacDinhDatPhong() {
    	
    	txtTienCoc.setText("0");
    	txtMaHD.setText(maHoaDonMoi());
//    	LocalDate ngayHienTai = LocalDate.now();
//    	txtNgayNhanPhong.setText(ngayHienTai.format(DateTimeFormatter.ofPattern("dd-MM-yyyy")));
//    	jDateChooser1.setDate(ngayHienTai);
//    	String ngay = new SimpleDateFormat("dd-mm-yyyy").format(new Date(ngayHienTai));
    	Timestamp ngay = new Timestamp(System.currentTimeMillis());
    	ngayDatPhong.setDate(ngay);
    	ngayTraPhong.setDate(ngay);
    }
    
    public void loadCBXLoaiPhong() {
    	cbxLoaiPhong.removeAllItems();
    	ArrayList<LoaiPhong> listLP = DAO_LoaiPhong.getAllLoaiPhong();
    	for (LoaiPhong lp : listLP) {
			cbxLoaiPhong.addItem(lp.getTenLP());
		}
    }
    
    public String getGiaTheoTenLP(String tenLP) {
    	ArrayList<LoaiPhong> listLP = DAO_LoaiPhong.getAllLoaiPhong();
    	for (LoaiPhong lp : listLP) {
    		if(lp.getTenLP().equalsIgnoreCase(tenLP)) {
    			Locale localeVN = new Locale("vi", "VN");
    		    NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
    		    String giaLP = currencyVN.format(lp.getGiaLP());
//    			BigDecimal giaLP = new BigDecimal(lp.getGiaLP()).setScale(0, BigDecimal.ROUND_HALF_UP);
    			return giaLP;
    		}
    	}
    	return "";
    }
    
    public String getGiaLP(String maLP) {
    	ArrayList<LoaiPhong> listLP = DAO_LoaiPhong.getAllLoaiPhong();
    	for (LoaiPhong lp : listLP) {
    		if(lp.getMaLP().equalsIgnoreCase(maLP)) {
    			Locale localeVN = new Locale("vi", "VN");
    		    NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
    		    String giaLP = currencyVN.format(lp.getGiaLP());
    			return giaLP;
    		}
    	}
    	return "";
    }
    
    public void loadCBXSoPhong() {
    	String loaiPhong;
    	cbxTenPhong.removeAllItems();
    	loaiPhong = (String)cbxLoaiPhong.getSelectedItem();
    	try {
    		Database.getInstance().connect();
			Connection conn = Database.getConnection();
			String sql = "select * \n"
					+ "from Phong p join LoaiPhong lp on p.malp = lp.malp\n"
					+ " where lp.tenlp=N'" + loaiPhong + "' and tinhTrang=N'Còn Trống'";
			PreparedStatement pstm = conn.prepareStatement(sql);
			ResultSet rs= pstm.executeQuery();
			while(rs.next()) {
				cbxTenPhong.addItem(rs.getString("TenPhong"));
				txtGiaPhong.setText(getGiaLP((rs.getString("maLP"))));
			}
			
    	} catch(Exception e){
    		JOptionPane.showMessageDialog(null, e);
    	}
    }
    
    public void timKH(String ten) {
		ArrayList<KhachHang> list = DAO_KhachHang.timKH(ten);
		modelDSKH.setRowCount(0);
		for (KhachHang kh : list) {
			modelDSKH.addRow(new Object[] {
					kh.getMaKH(),kh.getTenKH(),
					kh.getSoCMND(),kh.getSoDT()});}
    }
    
    public boolean DatPhong() throws Exception {
    	String maHD, maKH;
    	int i = tblDSKH.getSelectedRow();
    	
    	//Timestamp ngayLapHD = new Timestamp(System.currentTimeMillis());
    	if(i!=-1) {
    		if(kiemtradulieu()) {
    			maHD = txtMaHD.getText();
               	maKH = String.valueOf(tblDSKH.getValueAt(i,0));

//               	ArrayList<HoaDon> listHD = DAO_HoaDon.getAllHoaDon();
               	HoaDon hd = new HoaDon(maHD,new KhachHang(maKH));
               	if(!DAO_HoaDon.themHD(hd)) {
               		return false;            	
               	}
               	themPhieuThue(maHD);
            	JOptionPane.showMessageDialog(rootPane, "Đặt phòng thành công","Thông báo!", JOptionPane.INFORMATION_MESSAGE);

    		}
    		

    	}
    	else {
    		JOptionPane.showMessageDialog(rootPane, "Chưa chọn khách hàng !", "Lỗi!", JOptionPane.WARNING_MESSAGE);
    		return false;
    	}
    	return true;
    }
    
    public boolean themPhieuThue(String maHD) throws Exception{
    	String tenPhong,soTienCoc, maPhong;
    	double tienCoc;
    	if(kiemtradulieu()) {
    		soTienCoc= txtTienCoc.getText();
        	tienCoc= Double.valueOf(soTienCoc);
        	tenPhong = cbxTenPhong.getSelectedItem()+"";
        	maPhong= layMaPhongTheoTenPhong(tenPhong);
//        	LocalDateTime ngayDatPhong = LocalDateTime.now();  
//        	Timestamp ngayDatPhong = new Timestamp(System.currentTimeMillis());
//        	Timestamp ngay = new Timestamp(System.currentTimeMillis());
//        	new SimpleDateFormat("dd-MM-yyyy").format(jDateChooser1.getTime());
        	Timestamp ngaydatchoose = new Timestamp(ngayDatPhong.getDate().getTime());
        	Timestamp ngaytrachoose = new Timestamp(ngayTraPhong.getDate().getTime());
        	
        	PhieuThue pt = new PhieuThue(new Phong(maPhong),new HoaDon(maHD), ngaydatchoose,ngaytrachoose, tienCoc);
        	if(!DAO_PhieuThue.themPhieuThue(pt)) {
        		return false;
        	}
        	DAO_Phong.capNhatTinhTrangPhongDat(pt.getPhong());
    	}
    	return true;
    	
    }
    
    public String dinhDangTienTe(double tien) {
    	Locale localeVN = new Locale("vi", "VN");
	    NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
    	return currencyVN.format(tien);
    }
    
    
   
    public String maHoaDonMoi() {
    	ArrayList<HoaDon> listHD = DAO_HoaDon.getAllHoaDon();
    	if(listHD.size()==0) {
    		return "HD001";
    	}
    	
    	String ma = listHD.get(listHD.size()-1).getMaHD().substring(2);
    	
    	int i = Integer.parseInt(ma) + 1;
    	
    	if(i<10)
    		ma = "00" + i;
    	else if(i>=10 && i<=99)
    		ma = "0" + i;
    	else if(i>=100)
    		ma = i+"";
    	return "HD"+ma;
    }
    public boolean kiemtradulieu() {
    	
		Timestamp s1 = new Timestamp(ngayDatPhong.getDate().getTime());
		Timestamp s2 = new Timestamp(ngayTraPhong.getDate().getTime());
		
		double s3 = s2.getTime() - s1.getTime();
		
		if(s3 <= 0) {
			JOptionPane.showMessageDialog(this, "Ngày trả phòng phải lớn hơn ngày đặt phòng");
			return false;
		}
		if(cbxTenPhong.getSelectedItem() == null) {
			JOptionPane.showMessageDialog(this, "Hết phòng");
			return false;
		}
		
    	return true;
    }
    
    
 
    
    public String layMaLPTheoTenLP(String tenLP) {
    	ArrayList<LoaiPhong> listLP = DAO_LoaiPhong.getAllLoaiPhong();
    	for (LoaiPhong lp : listLP) {
			if(tenLP.equalsIgnoreCase(lp.getTenLP())) {
				return lp.getMaLP();}
		}
    	return "";
    }
    
    public String layMaPhongTheoTenPhong(String tenPhong) {
    	ArrayList<Phong> listP = DAO_Phong.getAllPhong();
    	for(Phong p : listP) {
    		if(p.getTenPhong().equalsIgnoreCase(tenPhong)) 
    			return p.getMaPhong();
    	}
    	return "";
    }
    
    public void setGiaTriMacDinh() {
    	txtMaHD.setText(maHoaDonMoi());
    	txtMaKH.setText("");
    	txtTenKH.setText("");
    	txtCMND.setText("");
    	txtSDT.setText("");
    	txtTienCoc.setText("0");
//        LocalDateTime ngayHienTai = LocalDateTime.now();
//        txtNgayNhanPhong.setText(ngayHienTai.format(DateTimeFormatter.ofPattern("dd-MM-yyyy hh:mm:ss")));
    	loadCBXLoaiPhong();
    	loadCBXSoPhong();
    }
    
   
    public void taiLaiDSKH() {
    	DocDuLieuDatabaseVaoTableDSKH();
    	txtTim.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_DatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_DatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_DatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_DatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_DatPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatPhong;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JComboBox<String> cbxLoaiPhong;
    private javax.swing.JComboBox<String> cbxTenPhong;
    private javax.swing.JScrollPane crollDSKH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JPanel lblDSKH;
    private javax.swing.JLabel lblDatPhong;
    private javax.swing.JLabel lblTTKH;
    private javax.swing.JLabel lblTieuDeDSKH;
    private com.toedter.calendar.JDateChooser ngayDatPhong;
    private com.toedter.calendar.JDateChooser ngayTraPhong;
    private javax.swing.JPanel pnlDatPhong;
    private javax.swing.JTable tblDSKH;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtGiaPhong;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTienCoc;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables

}
