/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.sql.Date;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import dao.DAO_ChucVu;
import dao.DAO_DichVu;
import dao.DAO_DichVuSuDung;
import dao.DAO_DonVi;
import dao.DAO_HoaDon;
import dao.DAO_KhachHang;
import dao.DAO_LoaiDichVu;
import dao.DAO_LoaiPhong;
import dao.DAO_NhanVien;
import dao.DAO_PhieuThue;
import dao.DAO_Phong;
import entity.ChucVu;
import entity.DichVu;
import entity.DichVuSuDung;
import entity.DonVi;
import entity.HoaDon;
import entity.KhachHang;
import entity.LoaiDichVu;
import entity.LoaiPhong;
import entity.NhanVien;
import entity.PhieuThue;
import entity.Phong;

/**
 *
 * @author admin
 */
public class GD_QuanLyHoaDon extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;


	/**
     * Creates new form GD_QuanLyHoaDon
     */
    public GD_QuanLyHoaDon() {
        initComponents();
        setExtendedState(GD_QuanLyHoaDon.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private DefaultTableModel modelHDDTT,modelDSP,modelDSDV;
    private String[] colsHDDTT = {"Mã HĐ","NV Thanh Toán","Tên Khách","Ngày Lập HĐ","Tổng Tiền"};
    private String[] colsDSP = {"Mã PT","Tên Phòng","Loại Phòng","Ngày Đặt Phòng","Ngày Trả Phòng","Tiền Phòng","Tiền Cọc"};
    private String[] colsDSDV = {"Tên DV","Loại DV","Đơn vị tính","Số lượng","Đơn giá","Thành Tiền"};
    
    
    public void DocDuLieuDatabaseVaoDSHD(){
    	ArrayList<HoaDon> list = DAO_HoaDon.getAllHoaDonDaThanhToan();
    	for(HoaDon hd : list) {
    		modelHDDTT.addRow(new Object[] {
    				hd.getMaHD(),
    				getTenNV(hd.getNhanVien().getMaNV()),
    				getTenKH(hd.getKhachHang().getMaKH()),
    				hd.getNgayLapHD(),
    				dinhDangTienTe(hd.getTongThanhTien()),
    				
    		});
    	}
    }
    
    public void DocDuLieuDatabaseVaoTableDSP() {
    	int i = tblDSHD.getSelectedRow();
    	
    	try {
    		
    		HoaDon hd = new HoaDon(String.valueOf(tblDSHD.getValueAt(i, 0)));
    		ArrayList<PhieuThue> listPT = DAO_PhieuThue.getAllPhieuThueTheoMaHD(hd.getMaHD());
        	
        		for (PhieuThue pt : listPT) {
        			modelDSP.addRow(new Object[] {
        				pt.getMaPT(),
        				getTenPhong(pt.getPhong().getMaPhong()),
        				getTenLoaiPhong(pt.getPhong().getLoaiPhong().getMaLP()),
        				new SimpleDateFormat("dd-MM-yyyy hh:mm:ss").format(new Date(pt.getNgayDatPhong().getTime())),
        				new SimpleDateFormat("dd-MM-yyyy hh:mm:ss").format(new Date(pt.getNgayTraPhong().getTime())),
        				dinhDangTienTe(pt.getTienPhong()),
        				dinhDangTienTe(pt.getTienCoc())
        				
        			});
        		}
        	
		} catch (Exception e) {
			// TODO: handle exception
		}	
    }
    
    public void DocDuLieuDatabaseVaoTableDSDV() {
    	int i = tblDSP.getSelectedRow();
    	
    	try {
    		PhieuThue pt = new PhieuThue(Integer.parseInt(String.valueOf(tblDSP.getValueAt(i, 0))));
    		
    		ArrayList<DichVuSuDung> listDVSD = DAO_DichVuSuDung.getAllHDDV(pt.getMaPT());
        	
        		for (DichVuSuDung dv : listDVSD) {
        			modelDSDV.addRow(new Object[] {
        				getTenDV(dv.getDichVu().getMaDV()),
        				getLoaiDV(dv.getDichVu().getLoaiDichVu().getMaLoaiDichVu()),
        				getDonVi(dv.getDichVu().getDonVi().getMaDonVi()),
        				dv.getSoLuong(),
        				dinhDangTienTe(getGiaDV(dv.getDichVu().getMaDV())),
        				dinhDangTienTe(dv.getSoLuong()*getGiaDV(dv.getDichVu().getMaDV()))
        			});
        		}
        	
		} catch (Exception e) {
			// TODO: handle exception
		}	
    }
    
    public double getGiaDV(String maDV) {
    	ArrayList<DichVu> listDV = DAO_DichVu.getAllDichVu();
    	for (DichVu dv : listDV) {
    		if(dv.getMaDV().equalsIgnoreCase(maDV)) {
//    			BigDecimal giaLP = new BigDecimal(lp.getGiaLP()).setScale(0, BigDecimal.ROUND_HALF_UP);
    			return dv.getGiaDV();
    		}
    	}
    	return 0;
    }
    public String getDonVi(String maDV) {
    	ArrayList<DonVi> listKH = DAO_DonVi.getAllDonVi();
    	for (DonVi kh : listKH) {
    		if(kh.getMaDonVi().equalsIgnoreCase(maDV))
    			return kh.getTenDonVi();
    	}
    	return "";
    }
    public String getLoaiDV(String maDV) {
    	ArrayList<LoaiDichVu> listKH = DAO_LoaiDichVu.getAllLoaiDV();
    	for (LoaiDichVu kh : listKH) {
    		if(kh.getMaLoaiDichVu().equalsIgnoreCase(maDV))
    			return kh.getTenLoaiDichVu();
    	}
    	return "";
    }
    public String getTenDV(String maDV) {
    	ArrayList<DichVu> listKH = DAO_DichVu.getAllDichVu();
    	for (DichVu kh : listKH) {
    		if(kh.getMaDV().equalsIgnoreCase(maDV))
    			return kh.getTenDV();
    	}
    	return "";
    }
    
    public String dinhDangTienTe(double tien) {
    	Locale localeVN = new Locale("vi", "VN");
	    NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);
    	return currencyVN.format(tien);
    }
    public String getTenKH(String maKH) {
    	ArrayList<KhachHang> listKH = DAO_KhachHang.getAllKhachHang();
    	for (KhachHang kh : listKH) {
    		if(kh.getMaKH().equalsIgnoreCase(maKH))
    			return kh.getTenKH();
    	}
    	return "";
    }
    
    public String getTenPhong(String maPhong) {
    	ArrayList<Phong> listP = DAO_Phong.getAllPhong();
    	for (Phong p : listP) {
    		if(p.getMaPhong().equalsIgnoreCase(maPhong))
    			return p.getTenPhong();
    	}
    	return "";
    }
    
    public String getTenLoaiPhong(String maLP) {
    	ArrayList<LoaiPhong> listP = DAO_LoaiPhong.getAllLoaiPhong();
    	for (LoaiPhong p : listP) {
    		if(p.getMaLP().equalsIgnoreCase(maLP))
    			return p.getTenLP();
    	}
    	return "";
    }
    
    public String getTenNV(String maNV) {
    	ArrayList<NhanVien> listNV = DAO_NhanVien.getAllNhanVien();
    	for (NhanVien nv : listNV) {
    		if(nv.getMaNV().equalsIgnoreCase(maNV))
    			return nv.getTenNV();
    	}
    	return "";
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlDSNV = new javax.swing.JPanel();
        scrollDSHD = new javax.swing.JScrollPane();
        tblDSHD = new javax.swing.JTable();
        lblDSHD = new javax.swing.JLabel();
        txtTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        scrollDSP = new javax.swing.JScrollPane();
        tblDSP = new javax.swing.JTable();
        scrollDSDV = new javax.swing.JScrollPane();
        tblDSDV = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        pnlBottom = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();
        lblTenNVLogin = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuPhong = new javax.swing.JMenu();
        PhongDangSuDung = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        DatPhong = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        QuanLyPhong = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        QuanLyLoaiPhong = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        menuDichVu = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        quanlyDV = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        quanLyLoaiDV = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        quanLyDonVi = new javax.swing.JMenuItem();
        menuKhachHang = new javax.swing.JMenu();
        quanLyKH = new javax.swing.JMenuItem();
        menuNhanVien = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        quanLyNhanVien = new javax.swing.JMenuItem();
        menuHoaDon = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        quanLyHoaDon = new javax.swing.JMenuItem();
        menuThongKe = new javax.swing.JMenu();
        tkBieuDo = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlDSNV.setBackground(new java.awt.Color(102, 204, 255));

        tblDSHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Tên Khách", "Ngày Lập HĐ", "Ngày Nhận Phòng", "Ngày Trả Phòng", "Tiền Phòng", "Tiền Dịch Vụ", "Tổng Tiền", "Tình Trạng"
            }
        ));
        scrollDSHD.setViewportView(tblDSHD);

        lblDSHD.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDSHD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDSHD.setText("DANH SÁCH HOÁ ĐƠN");

        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTim.setIcon(new javax.swing.ImageIcon("C:\\hotels (4)\\hotels\\src\\main\\java\\images\\ic_search.png")); // NOI18N
        btnTim.setText("TÌM");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon("C:\\hotels (4)\\hotels\\src\\main\\java\\images\\ic_refresh.png")); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DANH SÁCH PHÒNG");

        tblDSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã PT", "Tên Phòng", "Loại Phòng", "Tiền Phòng"
            }
        ));
        scrollDSP.setViewportView(tblDSP);

        tblDSDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên DV", "Đơn Vị", "Giá Tiền", "Số Lượng", "Tiền Dịch Vụ"
            }
        ));
        scrollDSDV.setViewportView(tblDSDV);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("DANH SÁCH DỊCH VỤ");

        javax.swing.GroupLayout pnlDSNVLayout = new javax.swing.GroupLayout(pnlDSNV);
        pnlDSNV.setLayout(pnlDSNVLayout);
        pnlDSNVLayout.setHorizontalGroup(
            pnlDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDSNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollDSHD, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDSHD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlDSNVLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlDSNVLayout.createSequentialGroup()
                        .addGroup(pnlDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDSNVLayout.createSequentialGroup()
                                .addGap(308, 308, 308)
                                .addComponent(jLabel1))
                            .addComponent(scrollDSP, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDSNVLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollDSDV, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDSNVLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(211, 211, 211)))))
                .addContainerGap())
        );
        pnlDSNVLayout.setVerticalGroup(
            pnlDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDSNVLayout.createSequentialGroup()
                .addComponent(lblDSHD)
                .addGap(15, 15, 15)
                .addGroup(pnlDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollDSHD, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollDSDV, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(scrollDSP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBottom.setBackground(new java.awt.Color(102, 204, 255));

        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnDangXuatActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        lblTenNVLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTenNVLogin.setText("họ tên nhân viên");
        lblTenNVLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTenNVLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTenNVLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(lblTenNVLogin))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDSNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDSNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Menu.setPreferredSize(new java.awt.Dimension(94, 60));

        jMenu1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\logo.png")); // NOI18N
        jMenu1.setActionCommand("HV HOTEL");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu1.setMinimumSize(new java.awt.Dimension(100, 45));
        jMenu1.setPreferredSize(new java.awt.Dimension(100, 45));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        Menu.add(jMenu1);

        menuPhong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuPhong.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_room.png")); // NOI18N
        menuPhong.setText("   PHÒNG");
        menuPhong.setToolTipText("");
        menuPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuPhong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuPhong.setMinimumSize(new java.awt.Dimension(190, 52));
        menuPhong.setPreferredSize(new java.awt.Dimension(180, 45));
        menuPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPhongActionPerformed(evt);
            }
        });

        PhongDangSuDung.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        PhongDangSuDung.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_phong.png")); // NOI18N
        PhongDangSuDung.setText("PHÒNG");
        PhongDangSuDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhongDangSuDungActionPerformed(evt);
            }
        });
        menuPhong.add(PhongDangSuDung);
        menuPhong.add(jSeparator12);

        DatPhong.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        DatPhong.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_datPhong.png")); // NOI18N
        DatPhong.setText("ĐẶT PHÒNG");
        DatPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatPhongActionPerformed(evt);
            }
        });
        menuPhong.add(DatPhong);
        menuPhong.add(jSeparator13);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_checkout (1).png")); // NOI18N
        jMenuItem3.setText("TRẢ PHÒNG");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuPhong.add(jMenuItem3);
        menuPhong.add(jSeparator1);

        QuanLyPhong.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        QuanLyPhong.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_phong.png")); // NOI18N
        QuanLyPhong.setText("QUẢN LÝ PHÒNG");
        QuanLyPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuanLyPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanLyPhongActionPerformed(evt);
            }
        });
        menuPhong.add(QuanLyPhong);
        menuPhong.add(jSeparator2);

        QuanLyLoaiPhong.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        QuanLyLoaiPhong.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_phong.png")); // NOI18N
        QuanLyLoaiPhong.setText("QUẢN LÝ LOẠI PHÒNG");
        QuanLyLoaiPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuanLyLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanLyLoaiPhongActionPerformed(evt);
            }
        });
        menuPhong.add(QuanLyLoaiPhong);
        menuPhong.add(jSeparator11);

        Menu.add(menuPhong);

        menuDichVu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuDichVu.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_service.png")); // NOI18N
        menuDichVu.setText("DỊCH VỤ");
        menuDichVu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuDichVu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuDichVu.setPreferredSize(new java.awt.Dimension(180, 34));
        menuDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDichVuActionPerformed(evt);
            }
        });
        menuDichVu.add(jSeparator3);

        quanlyDV.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanlyDV.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_list.png")); // NOI18N
        quanlyDV.setText("QUẢN LÝ DỊCH VỤ");
        quanlyDV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanlyDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanlyDVActionPerformed(evt);
            }
        });
        menuDichVu.add(quanlyDV);
        menuDichVu.add(jSeparator7);
        menuDichVu.add(jSeparator8);

        quanLyLoaiDV.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyLoaiDV.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_list.png")); // NOI18N
        quanLyLoaiDV.setText("QUẢN LÝ LOẠI DỊCH VỤ");
        quanLyLoaiDV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyLoaiDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyLoaiDVActionPerformed(evt);
            }
        });
        menuDichVu.add(quanLyLoaiDV);
        menuDichVu.add(jSeparator9);

        quanLyDonVi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyDonVi.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_list.png")); // NOI18N
        quanLyDonVi.setText("QUẢN LÝ ĐƠN VỊ");
        quanLyDonVi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyDonVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyDonViActionPerformed(evt);
            }
        });
        menuDichVu.add(quanLyDonVi);

        Menu.add(menuDichVu);

        menuKhachHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuKhachHang.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_customer.png")); // NOI18N
        menuKhachHang.setText("KHÁCH HÀNG");
        menuKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuKhachHang.setPreferredSize(new java.awt.Dimension(205, 34));

        quanLyKH.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyKH.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_list.png")); // NOI18N
        quanLyKH.setText("QUẢN LÝ KHÁCH HÀNG");
        quanLyKH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyKHActionPerformed(evt);
            }
        });
        menuKhachHang.add(quanLyKH);

        Menu.add(menuKhachHang);

        menuNhanVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuNhanVien.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_employee.png")); // NOI18N
        menuNhanVien.setText("NHÂN VIÊN");
        menuNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuNhanVien.setMaximumSize(new java.awt.Dimension(185, 32767));
        menuNhanVien.setPreferredSize(new java.awt.Dimension(180, 34));
        menuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhanVienActionPerformed(evt);
            }
        });
        menuNhanVien.add(jSeparator4);

        quanLyNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyNhanVien.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_list.png")); // NOI18N
        quanLyNhanVien.setText("QUẢN LÝ NHÂN VIÊN");
        quanLyNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyNhanVienActionPerformed(evt);
            }
        });
        menuNhanVien.add(quanLyNhanVien);

        Menu.add(menuNhanVien);

        menuHoaDon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuHoaDon.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_oder.png")); // NOI18N
        menuHoaDon.setText("  HOÁ ĐƠN");
        menuHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuHoaDon.setPreferredSize(new java.awt.Dimension(180, 34));
        menuHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHoaDonMouseClicked(evt);
            }
        });
        menuHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHoaDonActionPerformed(evt);
            }
        });
        menuHoaDon.add(jSeparator5);

        quanLyHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyHoaDon.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_list.png")); // NOI18N
        quanLyHoaDon.setText("QUẢN LÝ HOÁ ĐƠN");
        quanLyHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyHoaDonActionPerformed(evt);
            }
        });
        menuHoaDon.add(quanLyHoaDon);

        Menu.add(menuHoaDon);

        menuThongKe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuThongKe.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_chart_1.png")); // NOI18N
        menuThongKe.setText(" THỐNG KÊ");
        menuThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuThongKe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuThongKe.setPreferredSize(new java.awt.Dimension(180, 34));
        menuThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuThongKeMouseClicked(evt);
            }
        });
        menuThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThongKeActionPerformed(evt);
            }
        });

        tkBieuDo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tkBieuDo.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_chart.png")); // NOI18N
        tkBieuDo.setText("BIỂU ĐỒ");
        tkBieuDo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tkBieuDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkBieuDoActionPerformed(evt);
            }
        });
        menuThongKe.add(tkBieuDo);
        menuThongKe.add(jSeparator6);

        Menu.add(menuThongKe);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
        
        modelHDDTT = new DefaultTableModel(colsHDDTT,0);
        tblDSHD = new JTable(modelHDDTT);
        scrollDSHD.setViewportView(tblDSHD);
        
        ListSelectionModel listSelectionModelDSPhongDat = tblDSHD.getSelectionModel();
        
        listSelectionModelDSPhongDat.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        listSelectionModelDSPhongDat.addListSelectionListener(new ListSelectionListener() {
      	   @Override
      	   public void valueChanged(ListSelectionEvent e) {   
      		   modelDSP.setRowCount(0);
      		   DocDuLieuDatabaseVaoTableDSP();
      	   }
      });
        
        modelDSP = new DefaultTableModel(colsDSP,0);
        tblDSP = new JTable(modelDSP);
        scrollDSP.setViewportView(tblDSP);
        
        ListSelectionModel listSelectionModelDSDV = tblDSP.getSelectionModel();
        
        listSelectionModelDSDV.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        listSelectionModelDSDV.addListSelectionListener(new ListSelectionListener() {
      	   @Override
      	   public void valueChanged(ListSelectionEvent e) {   
      		   modelDSDV.setRowCount(0);
      		   DocDuLieuDatabaseVaoTableDSDV();
      	   }
      });
        
        modelDSDV = new DefaultTableModel(colsDSDV,0);
        tblDSDV = new JTable(modelDSDV);
        scrollDSDV.setViewportView(tblDSDV);
        
        setDefaultCloseOperation(0);
        hienThiNVDN();
        
        if(quanLy()) {
        	lblTenNVLogin.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    lblTenNVLoginMouseClicked(evt);
                }
            });
        }
        else
        	lblTenNVLogin.setEnabled(false);
        
        
        DocDuLieuDatabaseVaoDSHD();
    }// </editor-fold>//GEN-END:initComponents
    
//    setDefaultCloseOperation(0);
//    
//    modelHDDTT = new DefaultTableModel(colsHDDTT,0);
//    tblDSHD = new JTable(modelHDDTT);
//    scrollDSHD.setViewportView(tblDSHD);
//    
//    ListSelectionModel listSelectionModelDSPhongDat = tblDSHD.getSelectionModel();
//    
//    listSelectionModelDSPhongDat.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
//    
//    listSelectionModelDSPhongDat.addListSelectionListener(new ListSelectionListener() {
//  	   @Override
//  	   public void valueChanged(ListSelectionEvent e) {   
//  		   modelDSP.setRowCount(0);
//  		   DocDuLieuDatabaseVaoTableDSP();
//  	   }
//  });
//    
//    modelDSP = new DefaultTableModel(colsDSP,0);
//    tblDSP = new JTable(modelDSP);
//    scrollDSP.setViewportView(tblDSP);
//    
//    ListSelectionModel listSelectionModelDSDV = tblDSP.getSelectionModel();
//    
//    listSelectionModelDSDV.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
//    
//    listSelectionModelDSDV.addListSelectionListener(new ListSelectionListener() {
//  	   @Override
//  	   public void valueChanged(ListSelectionEvent e) {   
//  		   modelDSDV.setRowCount(0);
//  		   DocDuLieuDatabaseVaoTableDSDV();
//  	   }
//  });
//    
//    modelDSDV = new DefaultTableModel(colsDSDV,0);
//    tblDSDV = new JTable(modelDSDV);
//    scrollDSDV.setViewportView(tblDSDV);
//    
//    hienThiNVDN();
//    
//    if(quanLy()) {
//    	lblTenNVLogin.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                lblTenNVLoginMouseClicked(evt);
//            }
//        });
//    }
//    else
//    	lblTenNVLogin.setEnabled(false);
//    
//    
//    DocDuLieuDatabaseVaoDSHD();
    
    
    public void hienThiNVDN() {
    	NhanVien nv = DAO_NhanVien.getNhanVienDangLogin();
		lblTenNVLogin.setText(getTenChucVu(nv.getChucVu().getMaCV())+" - " + nv.getTenNV());
    }
    public boolean quanLy() {
    	NhanVien nv = DAO_NhanVien.getNhanVienDangLogin();
    	if((nv.getChucVu().getMaCV()).equalsIgnoreCase("CV001")==true)
    		return true;
    	return false;
    }
    
    public String getTenChucVu(String maCV) {
    	ArrayList<ChucVu> lstChucVu = DAO_ChucVu.getAllChucVu();
    	for (ChucVu cv : lstChucVu) {
    		if(cv.getMaCV().equalsIgnoreCase(maCV))
    			return cv.getTenCV();
    	}
    	return "";
    }
    
    public void timHD(String ten) {
    	ArrayList<HoaDon> list = DAO_HoaDon.timHDDaThanhToan(ten);
		if(list.size()==0) {
			JOptionPane.showMessageDialog(rootPane, "Không tìm thấy!", "Lỗi!", JOptionPane.WARNING_MESSAGE);
			return;
		}
		for (HoaDon hd : list) {
	    		modelHDDTT.addRow(new Object[] {
	    				hd.getMaHD(),
	    				getTenNV(hd.getNhanVien().getMaNV()),
	    				getTenKH(hd.getKhachHang().getMaKH()),
	    				hd.getNgayLapHD(),
	    				dinhDangTienTe(hd.getTongThanhTien()),
	    		});}
    }
    
    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
    	 String ten = txtTim.getText().replaceAll("\\s\\s+", " ").trim();
         modelHDDTT.setRowCount(0);
         timHD(ten);
    }//GEN-LAST:event_btnTimActionPerformed
    public void TaiLaiDSHD() {
    	modelDSP.setRowCount(0);
    	DocDuLieuDatabaseVaoDSHD();
    	txtTim.setText("");
    	txtTim.requestFocus();
    }
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
    	TaiLaiDSHD();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void lblTenNVLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTenNVLoginMouseClicked
        // TODO add your handling code here:
        GD_ThongTinNhanVien uiTTNV = new GD_ThongTinNhanVien();
        //    	this.setVisible(false);
        uiTTNV.setVisible(true);
    }//GEN-LAST:event_lblTenNVLoginMouseClicked

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
    	int result = JOptionPane.showConfirmDialog(rootPane,
                "Bạn có chắc muốn đăng xuất!",
                "XÁC NHẬN",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
        	GD_DangNhap uiLogout = new GD_DangNhap();
//        	GD_DaiSanh uiDaiSanh = new GD_DaiSanh();
            ArrayList<NhanVien> listNV = DAO_NhanVien.getAllNhanVien();
            for (NhanVien nv : listNV) {
    			if(nv.isTinhTrang()==true)
    				DAO_NhanVien.capNhatTinhTrangNVDX(nv);
    	        this.setVisible(false);
    	        uiLogout.setVisible(true);
    		}
            JOptionPane.showMessageDialog(rootPane, "Bạn đã đăng xuất!!!");
        } else if (result == JOptionPane.NO_OPTION) {
        	JOptionPane.showMessageDialog(rootPane, "Đăng xuất thất bại!!");
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        GD_DaiSanh uiSanh = new GD_DaiSanh();
        this.setVisible(false);
        uiSanh.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    	GD_DaiSanh uiMain = new GD_DaiSanh();
        this.setVisible(false);
        uiMain.setVisible(true);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void PhongDangSuDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhongDangSuDungActionPerformed
        // TODO add your handling code here:
        GD_Chinh ui = new GD_Chinh();
        this.setVisible(false);
        ui.setVisible(true);
    }//GEN-LAST:event_PhongDangSuDungActionPerformed

    private void DatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatPhongActionPerformed
        // TODO add your handling code here:
        GD_DatPhong uiDatPhong = new GD_DatPhong();

        uiDatPhong.setVisible(true);
    }//GEN-LAST:event_DatPhongActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        GD_TraPhong uiTraPhong = new GD_TraPhong();

        uiTraPhong.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void QuanLyPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanLyPhongActionPerformed
        // TODO add your handling code here:
        GD_QuanLyPhong uiQLP = new  GD_QuanLyPhong();
        this.setVisible(false);
        uiQLP.setVisible(true);
    }//GEN-LAST:event_QuanLyPhongActionPerformed

    private void QuanLyLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanLyLoaiPhongActionPerformed
        // TODO add your handling code here:
        GD_QuanLyLoaiPhong uiQLLoaiPhong = new GD_QuanLyLoaiPhong();
        this.setVisible(false);
        uiQLLoaiPhong.setVisible(true);
    }//GEN-LAST:event_QuanLyLoaiPhongActionPerformed

    private void menuPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPhongActionPerformed

    private void quanlyDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanlyDVActionPerformed
        // TODO add your handling code here:
        GD_QuanLyDichVu uiDV = new GD_QuanLyDichVu();
        this.setVisible(false);
        uiDV.setVisible(true);
    }//GEN-LAST:event_quanlyDVActionPerformed

    private void quanLyLoaiDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyLoaiDVActionPerformed
        // TODO add your handling code here:
        GD_QuanLyLoaiDichVu uiLoaiDV = new GD_QuanLyLoaiDichVu();
        this.setVisible(false);
        uiLoaiDV.setVisible(true);
    }//GEN-LAST:event_quanLyLoaiDVActionPerformed

    private void quanLyDonViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyDonViActionPerformed
        // TODO add your handling code here:
        GD_QuanLyDonVi uiDonVi = new GD_QuanLyDonVi();
        this.setVisible(false);
        uiDonVi.setVisible(true);
    }//GEN-LAST:event_quanLyDonViActionPerformed

    private void menuDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDichVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDichVuActionPerformed

    private void quanLyKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyKHActionPerformed
        GD_QuanLyKhachHang uiKH = new GD_QuanLyKhachHang();
        this.setVisible(false);
        uiKH.setVisible(true);
    }//GEN-LAST:event_quanLyKHActionPerformed

    private void quanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyNhanVienActionPerformed
        // TODO add your handling code here:
        GD_QuanLyNhanVien uiQLNV = new GD_QuanLyNhanVien();
        this.setVisible(false);
        uiQLNV.setVisible(true);
    }//GEN-LAST:event_quanLyNhanVienActionPerformed

    private void menuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuNhanVienActionPerformed

    private void quanLyHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyHoaDonActionPerformed
        GD_QuanLyHoaDon uiHD = new GD_QuanLyHoaDon();
        this.setVisible(false);
        uiHD.setVisible(true);
    }//GEN-LAST:event_quanLyHoaDonActionPerformed

    private void menuHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHoaDonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHoaDonMouseClicked

    private void menuHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHoaDonActionPerformed

    private void tkBieuDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkBieuDoActionPerformed
        // TODO add your handling code here:
        GD_ThongKeBieuDo uiTK = new GD_ThongKeBieuDo();
        this.setVisible(false);
        uiTK.setVisible(true);
    }//GEN-LAST:event_tkBieuDoActionPerformed

    private void menuThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuThongKeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuThongKeMouseClicked

    private void menuThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThongKeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_QuanLyHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DatPhong;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem PhongDangSuDung;
    private javax.swing.JMenuItem QuanLyLoaiPhong;
    private javax.swing.JMenuItem QuanLyPhong;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JLabel lblDSHD;
    private javax.swing.JLabel lblTenNVLogin;
    private javax.swing.JMenu menuDichVu;
    private javax.swing.JMenu menuHoaDon;
    private javax.swing.JMenu menuKhachHang;
    private javax.swing.JMenu menuNhanVien;
    private javax.swing.JMenu menuPhong;
    private javax.swing.JMenu menuThongKe;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlDSNV;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JMenuItem quanLyDonVi;
    private javax.swing.JMenuItem quanLyHoaDon;
    private javax.swing.JMenuItem quanLyKH;
    private javax.swing.JMenuItem quanLyLoaiDV;
    private javax.swing.JMenuItem quanLyNhanVien;
    private javax.swing.JMenuItem quanlyDV;
    private javax.swing.JScrollPane scrollDSDV;
    private javax.swing.JScrollPane scrollDSHD;
    private javax.swing.JScrollPane scrollDSP;
    private javax.swing.JTable tblDSDV;
    private javax.swing.JTable tblDSHD;
    private javax.swing.JTable tblDSP;
    private javax.swing.JMenuItem tkBieuDo;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
