/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.text.ParseException;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import dao.DAO_ChucVu;
import dao.DAO_DichVu;
import dao.DAO_DonVi;
import dao.DAO_LoaiDichVu;
import dao.DAO_NhanVien;
import entity.ChucVu;
import entity.DichVu;
import entity.DonVi;
import entity.LoaiDichVu;
import entity.NhanVien;

/**
 *
 * @author admin
 */
public class GD_QuanLyDichVu extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;


	/**
     * Creates new form GD_QuanLyDichVu
     */
    public GD_QuanLyDichVu() {
        initComponents();
        setExtendedState(GD_QuanLyDichVu.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private DefaultTableModel  modelDSDV;
    private String[] colsDSDV={"Mã DV","Tên DV","Loại Dịch Vụ","Đơn Vị Tính","Giá Tiền","Số Lượng Hiện Có"};
    
    
    public void DocDuLieuDatabaseVaoDSDV(){
    	ArrayList<DichVu> list = DAO_DichVu.getAllDichVu();
    	for(DichVu dv : list) {
    		modelDSDV.addRow(new Object[] {
    				dv.getMaDV(),
    				dv.getTenDV(),
    				getTenLoaiDV(dv.getLoaiDichVu().getMaLoaiDichVu()),
    				getTenDonVi(dv.getDonVi().getMaDonVi()),
    				dv.getGiaDV(),
    				dv.getSoLuongTon()
    		});
    	}
    }
    public String getTenLoaiDV(String maLoaiDV) {
    	ArrayList<LoaiDichVu> list = DAO_LoaiDichVu.getAllLoaiDV();
    	for (LoaiDichVu ldv : list) {
    		if(ldv.getMaLoaiDichVu().equalsIgnoreCase(maLoaiDV))
    			return ldv.getTenLoaiDichVu();
    	}
    	return "";
    }
    
    public String getTenDonVi(String maDonVi) {
    	ArrayList<DonVi> list = DAO_DonVi.getAllDonVi();
    	for (DonVi donVi : list) {
    		if(donVi.getMaDonVi().equalsIgnoreCase(maDonVi))
    			return donVi.getTenDonVi();
    	}
    	return "";
    }
    
   
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlTTNV = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGiaDV = new javax.swing.JTextField();
        txtMaDV = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTenDV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSoLuongTon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbxLDV = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbxDonVi = new javax.swing.JComboBox<>();
        pnlDSNV = new javax.swing.JPanel();
        scrollDSDV = new javax.swing.JScrollPane();
        tblDSDV = new javax.swing.JTable();
        lblDSLP = new javax.swing.JLabel();
        txtTim = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        pnlBottom = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();
        lblTenNVLogin = new javax.swing.JLabel();
        Menu1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuPhong = new javax.swing.JMenu();
        PhongDangSuDung = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        DatPhong = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        QuanLyPhong = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        QuanLyLoaiPhong = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        menuDichVu = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        quanlyDV = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        quanLyLoaiDV = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        quanLyDonVi = new javax.swing.JMenuItem();
        menuKhachHang = new javax.swing.JMenu();
        quanLyKH = new javax.swing.JMenuItem();
        menuNhanVien = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        quanLyNhanVien = new javax.swing.JMenuItem();
        menuHoaDon = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        quanLyHoaDon = new javax.swing.JMenuItem();
        menuThongKe = new javax.swing.JMenu();
        tkBieuDo = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlTTNV.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Mã Dịch Vụ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Tên Dịch Vụ");

        txtGiaDV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGiaDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaDVActionPerformed(evt);
            }
        });

        txtMaDV.setEditable(false);
        txtMaDV.setBackground(new java.awt.Color(204, 204, 204));
        txtMaDV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDVActionPerformed(evt);
            }
        });

        btnLamMoi.setText("LÀM MỚI");
        btnLamMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon("C:\\hotels (4)\\hotels\\src\\main\\java\\images\\ic_del.png")); // NOI18N
        btnXoa.setText("XOÁ");
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon("C:\\hotels (4)\\hotels\\src\\main\\java\\images\\ic_add.png")); // NOI18N
        btnThem.setText("THÊM");
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnThemActionPerformed(evt);
				} catch (ParseException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setIcon(new javax.swing.ImageIcon("C:\\hotels (4)\\hotels\\src\\main\\java\\images\\ic_upd.png")); // NOI18N
        btnCapNhat.setText("CẬP NHẬT");
        btnCapNhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnCapNhatActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("THÔNG TIN DỊCH VỤ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Giá Dịch Vụ");

        txtTenDV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Số Lượng Hiện Có");

        txtSoLuongTon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSoLuongTon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongTonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Loại Dịch Vụ");

        cbxLDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Đơn Vị Tính");

        cbxDonVi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnlTTNVLayout = new javax.swing.GroupLayout(pnlTTNV);
        pnlTTNV.setLayout(pnlTTNVLayout);
        pnlTTNVLayout.setHorizontalGroup(
            pnlTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTTNVLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSoLuongTon))
                    .addGroup(pnlTTNVLayout.createSequentialGroup()
                        .addGroup(pnlTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(61, 61, 61)
                        .addGroup(pnlTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaDV)
                            .addComponent(txtTenDV)
                            .addComponent(txtGiaDV)))
                    .addGroup(pnlTTNVLayout.createSequentialGroup()
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlTTNVLayout.createSequentialGroup()
                        .addGroup(pnlTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(58, 58, 58)
                        .addGroup(pnlTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxLDV, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxDonVi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(pnlTTNVLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCapNhat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addGap(16, 16, 16))
            .addGroup(pnlTTNVLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTTNVLayout.setVerticalGroup(
            pnlTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTTNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(35, 35, 35)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenDV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGiaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxLDV, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnlTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTTNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDSNV.setBackground(new java.awt.Color(102, 204, 255));

        tblDSDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Dịch Vụ", "Tên Dịch Vụ", "Giá Tiền", "Số Lượng Hiện Có", "Loại Dịch Vụ", "Đơn Vị Tính"
            }
        ));
        scrollDSDV.setViewportView(tblDSDV);

        lblDSLP.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDSLP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDSLP.setText("DANH SÁCH DỊCH VỤ");

        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTim.setIcon(new javax.swing.ImageIcon("C:\\hotels (4)\\hotels\\src\\main\\java\\images\\ic_search.png")); // NOI18N
        btnTim.setText("TÌM");
        btnTim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon("C:\\hotels (4)\\hotels\\src\\main\\java\\images\\ic_refresh.png")); // NOI18N
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDSNVLayout = new javax.swing.GroupLayout(pnlDSNV);
        pnlDSNV.setLayout(pnlDSNVLayout);
        pnlDSNVLayout.setHorizontalGroup(
            pnlDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDSNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDSNVLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTim)
                        .addGap(0, 327, Short.MAX_VALUE))
                    .addComponent(scrollDSDV)
                    .addComponent(lblDSLP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlDSNVLayout.setVerticalGroup(
            pnlDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDSNVLayout.createSequentialGroup()
                .addComponent(lblDSLP)
                .addGap(15, 15, 15)
                .addGroup(pnlDSNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollDSDV, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTTNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDSNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTTNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(pnlDSNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pnlBottom.setBackground(new java.awt.Color(102, 204, 255));

        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					btnDangXuatActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        lblTenNVLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTenNVLogin.setText("họ tên nhân viên");
        lblTenNVLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTenNVLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTenNVLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBottomLayout.createSequentialGroup()
                        .addComponent(lblTenNVLogin)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addContainerGap())
        );

        Menu1.setPreferredSize(new java.awt.Dimension(94, 60));

        jMenu2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenu2.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\logo.png")); // NOI18N
        jMenu2.setActionCommand("HV HOTEL");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jMenu2.setMinimumSize(new java.awt.Dimension(100, 45));
        jMenu2.setPreferredSize(new java.awt.Dimension(100, 45));
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        Menu1.add(jMenu2);

        menuPhong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuPhong.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_room.png")); // NOI18N
        menuPhong.setText("   PHÒNG");
        menuPhong.setToolTipText("");
        menuPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuPhong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuPhong.setMinimumSize(new java.awt.Dimension(190, 52));
        menuPhong.setPreferredSize(new java.awt.Dimension(180, 45));
        menuPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPhongActionPerformed(evt);
            }
        });

        PhongDangSuDung.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        PhongDangSuDung.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_phong.png")); // NOI18N
        PhongDangSuDung.setText("PHÒNG");
        PhongDangSuDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhongDangSuDungActionPerformed(evt);
            }
        });
        menuPhong.add(PhongDangSuDung);
        menuPhong.add(jSeparator12);

        DatPhong.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        DatPhong.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_datPhong.png")); // NOI18N
        DatPhong.setText("ĐẶT PHÒNG");
        DatPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatPhongActionPerformed(evt);
            }
        });
        menuPhong.add(DatPhong);
        menuPhong.add(jSeparator13);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_checkout (1).png")); // NOI18N
        jMenuItem3.setText("TRẢ PHÒNG");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuPhong.add(jMenuItem3);
        menuPhong.add(jSeparator1);

        QuanLyPhong.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        QuanLyPhong.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_phong.png")); // NOI18N
        QuanLyPhong.setText("QUẢN LÝ PHÒNG");
        QuanLyPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuanLyPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanLyPhongActionPerformed(evt);
            }
        });
        menuPhong.add(QuanLyPhong);
        menuPhong.add(jSeparator2);

        QuanLyLoaiPhong.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        QuanLyLoaiPhong.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_phong.png")); // NOI18N
        QuanLyLoaiPhong.setText("QUẢN LÝ LOẠI PHÒNG");
        QuanLyLoaiPhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuanLyLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuanLyLoaiPhongActionPerformed(evt);
            }
        });
        menuPhong.add(QuanLyLoaiPhong);
        menuPhong.add(jSeparator11);

        Menu1.add(menuPhong);

        menuDichVu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuDichVu.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_service.png")); // NOI18N
        menuDichVu.setText("DỊCH VỤ");
        menuDichVu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuDichVu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuDichVu.setPreferredSize(new java.awt.Dimension(180, 34));
        menuDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDichVuActionPerformed(evt);
            }
        });
        menuDichVu.add(jSeparator3);

        quanlyDV.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanlyDV.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_list.png")); // NOI18N
        quanlyDV.setText("QUẢN LÝ DỊCH VỤ");
        quanlyDV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanlyDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanlyDVActionPerformed(evt);
            }
        });
        menuDichVu.add(quanlyDV);
        menuDichVu.add(jSeparator7);
        menuDichVu.add(jSeparator8);

        quanLyLoaiDV.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyLoaiDV.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_list.png")); // NOI18N
        quanLyLoaiDV.setText("QUẢN LÝ LOẠI DỊCH VỤ");
        quanLyLoaiDV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyLoaiDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyLoaiDVActionPerformed(evt);
            }
        });
        menuDichVu.add(quanLyLoaiDV);
        menuDichVu.add(jSeparator9);

        quanLyDonVi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyDonVi.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_list.png")); // NOI18N
        quanLyDonVi.setText("QUẢN LÝ ĐƠN VỊ");
        quanLyDonVi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyDonVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyDonViActionPerformed(evt);
            }
        });
        menuDichVu.add(quanLyDonVi);

        Menu1.add(menuDichVu);

        menuKhachHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuKhachHang.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_customer.png")); // NOI18N
        menuKhachHang.setText("KHÁCH HÀNG");
        menuKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuKhachHang.setPreferredSize(new java.awt.Dimension(205, 34));

        quanLyKH.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyKH.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_list.png")); // NOI18N
        quanLyKH.setText("QUẢN LÝ KHÁCH HÀNG");
        quanLyKH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyKHActionPerformed(evt);
            }
        });
        menuKhachHang.add(quanLyKH);

        Menu1.add(menuKhachHang);

        menuNhanVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuNhanVien.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_employee.png")); // NOI18N
        menuNhanVien.setText("NHÂN VIÊN");
        menuNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuNhanVien.setMaximumSize(new java.awt.Dimension(185, 32767));
        menuNhanVien.setPreferredSize(new java.awt.Dimension(180, 34));
        menuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNhanVienActionPerformed(evt);
            }
        });
        menuNhanVien.add(jSeparator4);

        quanLyNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyNhanVien.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_list.png")); // NOI18N
        quanLyNhanVien.setText("QUẢN LÝ NHÂN VIÊN");
        quanLyNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyNhanVienActionPerformed(evt);
            }
        });
        menuNhanVien.add(quanLyNhanVien);

        Menu1.add(menuNhanVien);

        menuHoaDon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuHoaDon.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_oder.png")); // NOI18N
        menuHoaDon.setText("  HOÁ ĐƠN");
        menuHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuHoaDon.setPreferredSize(new java.awt.Dimension(180, 34));
        menuHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHoaDonMouseClicked(evt);
            }
        });
        menuHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHoaDonActionPerformed(evt);
            }
        });
        menuHoaDon.add(jSeparator5);

        quanLyHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        quanLyHoaDon.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_list.png")); // NOI18N
        quanLyHoaDon.setText("QUẢN LÝ HOÁ ĐƠN");
        quanLyHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quanLyHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyHoaDonActionPerformed(evt);
            }
        });
        menuHoaDon.add(quanLyHoaDon);

        Menu1.add(menuHoaDon);

        menuThongKe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuThongKe.setIcon(new javax.swing.ImageIcon("C:\\HocTap\\KLTN_T7\\KLTN_HV_Hotels\\src\\main\\java\\images\\ic_chart_1.png")); // NOI18N
        menuThongKe.setText(" THỐNG KÊ");
        menuThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuThongKe.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuThongKe.setPreferredSize(new java.awt.Dimension(180, 34));
        menuThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuThongKeMouseClicked(evt);
            }
        });
        menuThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThongKeActionPerformed(evt);
            }
        });

        tkBieuDo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tkBieuDo.setIcon(new javax.swing.ImageIcon("C:\\KLTN\\KLTN_HV_Hotel\\src\\main\\java\\images\\ic_chart.png")); // NOI18N
        tkBieuDo.setText("BIỂU ĐỒ");
        tkBieuDo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tkBieuDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkBieuDoActionPerformed(evt);
            }
        });
        menuThongKe.add(tkBieuDo);
        menuThongKe.add(jSeparator6);

        Menu1.add(menuThongKe);

        setJMenuBar(Menu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(pnlBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(0);
        // Model DSDV
           modelDSDV = new DefaultTableModel(colsDSDV,0);
           tblDSDV = new JTable(modelDSDV);
           scrollDSDV.setViewportView(tblDSDV);
           
           tblDSDV.getColumnModel().getColumn(0);
           tblDSDV.getColumnModel().getColumn(1);
           tblDSDV.getColumnModel().getColumn(2);
           tblDSDV.getColumnModel().getColumn(3);
           tblDSDV.getColumnModel().getColumn(4);
           tblDSDV.getColumnModel().getColumn(5);
           
           // Sự kiện click trên tblDSDV
           ListSelectionModel listSelectionModelDSDV = tblDSDV.getSelectionModel();
           // Thiết lập chỉ click được 1 dòng
           listSelectionModelDSDV.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
           // Xử lý sự kiện click
           listSelectionModelDSDV.addListSelectionListener(new ListSelectionListener() {
    			
    			@Override
    			public void valueChanged(ListSelectionEvent e) {
    				// TODO Auto-generated method stub
    					DocDuLieuVaoTextFiedDV();
    				}
    			
    		});
           loadCBXDonVi();
           loadCBXLoaiPhong();
           DocDuLieuDatabaseVaoDSDV();
           setResizable(false);
           hienThiNVDN();
           
           if(quanLy()) {
           	lblTenNVLogin.addMouseListener(new java.awt.event.MouseAdapter() {
                   public void mouseClicked(java.awt.event.MouseEvent evt) {
                       lblTenNVLoginMouseClicked(evt);
                   }
               });
           }
           else
           	lblTenNVLogin.setEnabled(false);
        
    }// </editor-fold>//GEN-END:initComponents

    
//    setDefaultCloseOperation(0);
//    // Model DSDV
//       modelDSDV = new DefaultTableModel(colsDSDV,0);
//       tblDSDV = new JTable(modelDSDV);
//       scrollDSDV.setViewportView(tblDSDV);
//       
//       tblDSDV.getColumnModel().getColumn(0);
//       tblDSDV.getColumnModel().getColumn(1);
//       tblDSDV.getColumnModel().getColumn(2);
//       tblDSDV.getColumnModel().getColumn(3);
//       tblDSDV.getColumnModel().getColumn(4);
//       tblDSDV.getColumnModel().getColumn(5);
//       
//       // Sự kiện click trên tblDSDV
//       ListSelectionModel listSelectionModelDSDV = tblDSDV.getSelectionModel();
//       // Thiết lập chỉ click được 1 dòng
//       listSelectionModelDSDV.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
//       // Xử lý sự kiện click
//       listSelectionModelDSDV.addListSelectionListener(new ListSelectionListener() {
//			
//			@Override
//			public void valueChanged(ListSelectionEvent e) {
//				// TODO Auto-generated method stub
//					DocDuLieuVaoTextFiedDV();
//				}
//			
//		});
//       loadCBXDonVi();
//       loadCBXLoaiPhong();
//       DocDuLieuDatabaseVaoDSDV();
//       setResizable(false);
//       hienThiNVDN();
//       
//       if(quanLy()) {
//       	lblTenNVLogin.addMouseListener(new java.awt.event.MouseAdapter() {
//               public void mouseClicked(java.awt.event.MouseEvent evt) {
//                   lblTenNVLoginMouseClicked(evt);
//               }
//           });
//       }
//       else
//       	lblTenNVLogin.setEnabled(false);
    
    public void hienThiNVDN() {
    	NhanVien nv = DAO_NhanVien.getNhanVienDangLogin();
		lblTenNVLogin.setText(getTenChucVu(nv.getChucVu().getMaCV())+" - " + nv.getTenNV());
    }
    public boolean quanLy() {
    	NhanVien nv = DAO_NhanVien.getNhanVienDangLogin();
    	if((nv.getChucVu().getMaCV()).equalsIgnoreCase("CV001")==true)
    		return true;
    	return false;
    }
    
    public String getTenChucVu(String maCV) {
    	ArrayList<ChucVu> lstChucVu = DAO_ChucVu.getAllChucVu();
    	for (ChucVu cv : lstChucVu) {
    		if(cv.getMaCV().equalsIgnoreCase(maCV))
    			return cv.getTenCV();
    	}
    	return "";
    }
    
    public String maDVMoi() {
    	ArrayList<DichVu> list = DAO_DichVu.getAllDichVu();
    	if(list.size()==0) {
    		return "DV001";
    	}
    	
    	String ma = list.get(list.size()-1).getMaDV().substring(2);
    	
    	int i = Integer.parseInt(ma) + 1;
    	
    	if(i<10)
    		ma = "00" + i;
    	else if(i>=10 && i<=99)
    		ma = "0" + i;
    	else if(i>=100)
    		ma = i+"";
    	return "DV"+ma;
    }
    
    public void setGiaTriMacDinhDV() {
    	txtMaDV.setText(maDVMoi());
    	txtTenDV.setText("");
    	txtGiaDV.setText("");
    	txtSoLuongTon.setText("");
    	cbxLDV.setSelectedIndex(0);
    	cbxDonVi.setSelectedIndex(0);
    	txtTenDV.requestFocus();
    	
    }
    
    public void LamMoiTextField() {
    	setGiaTriMacDinhDV();
    }
    public void taiLaiDSDV() {
    	modelDSDV.setRowCount(0);
    	DocDuLieuDatabaseVaoDSDV();
    	setGiaTriMacDinhDV();
    	txtTim.setText("");
    }
    
    public void loadCBXLoaiPhong() {
    	cbxLDV.removeAllItems();
    	ArrayList<LoaiDichVu> list = DAO_LoaiDichVu.getAllLoaiDV();
    	for (LoaiDichVu ldv : list) {
    		cbxLDV.addItem(ldv.getTenLoaiDichVu());
		}
    }
    
    public void loadCBXDonVi() {
    	cbxDonVi.removeAllItems();
    	ArrayList<DonVi> list = DAO_DonVi.getAllDonVi();
    	for (DonVi dv : list) {
    		cbxDonVi.addItem(dv.getTenDonVi());
		}
    }
    
    public void DocDuLieuVaoTextFiedDV()
    {
    	ArrayList<DichVu> list = DAO_DichVu.getAllDichVu();
		int i = tblDSDV.getSelectedRow();
		if(i!=-1) {
			DichVu dv = list.get(i);
			txtMaDV.setText(dv.getMaDV());
			txtTenDV.setText(dv.getTenDV());
			txtGiaDV.setText(String.valueOf(dv.getGiaDV()));
			txtSoLuongTon.setText(String.valueOf(dv.getSoLuongTon()));
			cbxLDV.setSelectedItem(getTenLoaiDV(dv.getLoaiDichVu().getMaLoaiDichVu()));
			cbxDonVi.setSelectedItem(getTenDonVi(dv.getDonVi().getMaDonVi()));
		}
    }
    
    
    
    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
    	setGiaTriMacDinhDV();

    }//GEN-LAST:event_btnLamMoiActionPerformed

    public boolean xoaDV() {
	
    	int result = JOptionPane.showConfirmDialog(rootPane,
                "Bạn có chắc muốn dịch vụ này!",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
        	DAO_DichVu.xoaDV(txtMaDV.getText());
        	JOptionPane.showMessageDialog(rootPane, "Xóa dịch vụ thành công!");
        	return true;
        } else if (result == JOptionPane.NO_OPTION) {
        	JOptionPane.showMessageDialog(rootPane, "Đã hủy thao tác xóa!");
        }
        return false;
    }
    
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    	xoaDV();
    	taiLaiDSDV();
    }//GEN-LAST:event_btnXoaActionPerformed

    public boolean themDV() throws ParseException {
    	String maDV, tenDV, loaiDV, donVi, maLDV, maDonVi;
    	Double giaDV;
    	int soLuongTon;
    	if(kiemTraDuLieuDV()) {
    		maDV = txtMaDV.getText();
        	tenDV = txtTenDV.getText();
//        	gia = txtGiaDV.getText();
        	giaDV= Double.parseDouble(txtGiaDV.getText());
//        	slt=txtSoLuongTon.getText();
        	soLuongTon = Integer.parseInt(txtSoLuongTon.getText());
        	loaiDV = cbxLDV.getSelectedItem()+"";
        	maLDV = layMaLDVTheoTen(loaiDV);
        	donVi = cbxDonVi.getSelectedItem()+"";
        	maDonVi = layMaDonViTheoTen(donVi);
        	
        	DichVu p = new DichVu(maDV, tenDV, giaDV, soLuongTon, new LoaiDichVu(maLDV), new DonVi(maDonVi) );
        	
        	if(!DAO_DichVu.themDV(p))
        		return false;
        	JOptionPane.showMessageDialog(rootPane, "Thêm dịch vụ thành công!");
        	modelDSDV.setRowCount(0);
        	DocDuLieuDatabaseVaoDSDV();
    	}
    	return true;
    }
    
    public String layMaLDVTheoTen(String tenLDV) {
    	ArrayList<LoaiDichVu> list = DAO_LoaiDichVu.getAllLoaiDV();
    	for (LoaiDichVu ldv : list) {
			if(tenLDV.equalsIgnoreCase(ldv.getTenLoaiDichVu()))
				return ldv.getMaLoaiDichVu();
		}
    	return "";
    }
    
    public String layMaDonViTheoTen(String tenDonVi) {
    	ArrayList<DonVi> list = DAO_DonVi.getAllDonVi();
    	for (DonVi dv : list) {
			if(tenDonVi.equalsIgnoreCase(dv.getTenDonVi()))
				return dv.getMaDonVi();
		}
    	return "";
    }
    
    public boolean kiemTraDuLieuDV() {
		String tenDV=txtTenDV.getText().trim();
//		String giaDV=txtGiaDV.getText().trim();
		int giaDV = 0;
		String gia = Integer.toString(giaDV);
		gia= txtGiaDV.getText().trim();
//		String soLuong = txtSoLuongTon.getText().trim();
		int soLuong = 0;
		String sl = Integer.toString(soLuong);
		sl = txtSoLuongTon.getText().trim();
		if (tenDV.trim().length() > 0) {
			if (!(tenDV.matches("[^.\\-\\/\\_\\+\\@\\!\\$\\^\\&\\*\\(\\)]+"))) {
				JOptionPane.showMessageDialog(this, "Tên dịch vụ không chứa ký tự đặc biệt");
				return false;
			}
		} else {
			JOptionPane.showMessageDialog(this, "Tên dịch vụ không được để trống");
			return false;
		}
		if (gia.trim().length()>0) {
			if (!(gia.matches("^[1-9]([0-9]{3,})"))) {
				JOptionPane.showMessageDialog(this, "Giá dịch vụ phải là số và lớn hơn bằng 1000");
				return false;
			}
		} else {
			JOptionPane.showMessageDialog(this, "Giá dịch vụ không được để trống");
			return false;
		}
		
		if (sl.trim().length()>0) {
			if (!(sl.matches("^[1-9]([0-9]{1,})"))) {
				JOptionPane.showMessageDialog(this, "Số lượng hiện có phải là số và lớn hơn 0");
				return false;
			}
		} else {
			JOptionPane.showMessageDialog(this, "Số lượng hiện có không được để trống");
			return false;
		}
		
		return true;
    }
    
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) throws ParseException {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    	themDV();

    }//GEN-LAST:event_btnThemActionPerformed

    public boolean capNhatDV() throws Exception {
    	String maDV, tenDV, loaiDV, donVi, maLDV, maDonVi;
    	Double giaDV;
    	int soLuongTon;
//    	if(kiemTraDuLieuDV())
//    	{
    		maDV = txtMaDV.getText();
        	tenDV = txtTenDV.getText();
//        	gia = txtGiaDV.getText();
        	giaDV= Double.parseDouble(txtGiaDV.getText());
//        	slt=txtSoLuongTon.getText();
        	soLuongTon = Integer.parseInt(txtSoLuongTon.getText());
        	loaiDV = cbxLDV.getSelectedItem()+"";
        	maLDV = layMaLDVTheoTen(loaiDV);
        	donVi = cbxDonVi.getSelectedItem()+"";
        	maDonVi = layMaDonViTheoTen(donVi);
        	
        	DichVu p = new DichVu(maDV, tenDV, giaDV, soLuongTon, new LoaiDichVu(maLDV), new DonVi(maDonVi) );
        	if(!DAO_DichVu.capNhatDV(p)) {
        		JOptionPane.showMessageDialog(rootPane, "Cập nhật không thành công!");
        		return false;
        	}
        	JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công!");
//    	}
    	
    	return true;
    }
    
    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        	capNhatDV();
        	taiLaiDSDV();
        
    }//GEN-LAST:event_btnCapNhatActionPerformed

    public void timDV(String ten) {
		ArrayList<DichVu> list = DAO_DichVu.timDV(ten);
		for (DichVu dv : list) {
			modelDSDV.addRow(new Object[] {
    				dv.getMaDV(),
    				dv.getTenDV(),
    				getTenLoaiDV(dv.getLoaiDichVu().getMaLoaiDichVu()),
    				getTenDonVi(dv.getDonVi().getMaDonVi()),
    				dv.getGiaDV(),
    				dv.getSoLuongTon()
    		});
		}
    }
    
    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
    	String ten = txtTim.getText().replaceAll("\\s\\s+", " ").trim();
    	modelDSDV.setRowCount(0);
    	timDV(ten);
    	setGiaTriMacDinhDV();

    }//GEN-LAST:event_btnTimActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
    	taiLaiDSDV();

    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
    	int result = JOptionPane.showConfirmDialog(rootPane,
                "Bạn có chắc muốn đăng xuất!",
                "XÁC NHẬN",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
        	GD_DangNhap uiLogout = new GD_DangNhap();
//        	GD_DaiSanh uiDaiSanh = new GD_DaiSanh();
            ArrayList<NhanVien> listNV = DAO_NhanVien.getAllNhanVien();
            for (NhanVien nv : listNV) {
    			if(nv.isTinhTrang()==true)
    				DAO_NhanVien.capNhatTinhTrangNVDX(nv);
    	        this.setVisible(false);
    	        uiLogout.setVisible(true);
    		}
            JOptionPane.showMessageDialog(rootPane, "Bạn đã đăng xuất!!!");
        } else if (result == JOptionPane.NO_OPTION) {
        	JOptionPane.showMessageDialog(rootPane, "Đăng xuất thất bại!!");
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void lblTenNVLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTenNVLoginMouseClicked
        // TODO add your handling code here:
        GD_ThongTinNhanVien uiTTNV = new GD_ThongTinNhanVien();
        //    	this.setVisible(false);
        uiTTNV.setVisible(true);
    }//GEN-LAST:event_lblTenNVLoginMouseClicked

    private void txtMaDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDVActionPerformed

    private void txtGiaDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaDVActionPerformed

    private void txtSoLuongTonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongTonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongTonActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        GD_DaiSanh uiSanh = new GD_DaiSanh();
        this.setVisible(false);
        uiSanh.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    	GD_DaiSanh uiMain = new GD_DaiSanh();
        this.setVisible(false);
        uiMain.setVisible(true);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void PhongDangSuDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhongDangSuDungActionPerformed
        // TODO add your handling code here:
        GD_Chinh ui = new GD_Chinh();
        this.setVisible(false);
        ui.setVisible(true);
    }//GEN-LAST:event_PhongDangSuDungActionPerformed

    private void DatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatPhongActionPerformed
        // TODO add your handling code here:
        GD_DatPhong uiDatPhong = new GD_DatPhong();

        uiDatPhong.setVisible(true);
    }//GEN-LAST:event_DatPhongActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        GD_TraPhong uiTraPhong = new GD_TraPhong();

        uiTraPhong.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void QuanLyPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanLyPhongActionPerformed
        // TODO add your handling code here:
        GD_QuanLyPhong uiQLP = new  GD_QuanLyPhong();
        this.setVisible(false);
        uiQLP.setVisible(true);
    }//GEN-LAST:event_QuanLyPhongActionPerformed

    private void QuanLyLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuanLyLoaiPhongActionPerformed
        // TODO add your handling code here:
        GD_QuanLyLoaiPhong uiQLLoaiPhong = new GD_QuanLyLoaiPhong();
        this.setVisible(false);
        uiQLLoaiPhong.setVisible(true);
    }//GEN-LAST:event_QuanLyLoaiPhongActionPerformed

    private void menuPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPhongActionPerformed

    private void quanlyDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanlyDVActionPerformed
        // TODO add your handling code here:
        GD_QuanLyDichVu uiDV = new GD_QuanLyDichVu();
        this.setVisible(false);
        uiDV.setVisible(true);
    }//GEN-LAST:event_quanlyDVActionPerformed

    private void quanLyLoaiDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyLoaiDVActionPerformed
        // TODO add your handling code here:
        GD_QuanLyLoaiDichVu uiLoaiDV = new GD_QuanLyLoaiDichVu();
        this.setVisible(false);
        uiLoaiDV.setVisible(true);
    }//GEN-LAST:event_quanLyLoaiDVActionPerformed

    private void quanLyDonViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyDonViActionPerformed
        // TODO add your handling code here:
        GD_QuanLyDonVi uiDonVi = new GD_QuanLyDonVi();
        this.setVisible(false);
        uiDonVi.setVisible(true);
    }//GEN-LAST:event_quanLyDonViActionPerformed

    private void menuDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDichVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDichVuActionPerformed

    private void quanLyKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyKHActionPerformed
        GD_QuanLyKhachHang uiKH = new GD_QuanLyKhachHang();
        this.setVisible(false);
        uiKH.setVisible(true);
    }//GEN-LAST:event_quanLyKHActionPerformed

    private void quanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyNhanVienActionPerformed
        // TODO add your handling code here:
        GD_QuanLyNhanVien uiQLNV = new GD_QuanLyNhanVien();
        this.setVisible(false);
        uiQLNV.setVisible(true);
    }//GEN-LAST:event_quanLyNhanVienActionPerformed

    private void menuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuNhanVienActionPerformed

    private void quanLyHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyHoaDonActionPerformed
        GD_QuanLyHoaDon uiHD = new GD_QuanLyHoaDon();
        this.setVisible(false);
        uiHD.setVisible(true);
    }//GEN-LAST:event_quanLyHoaDonActionPerformed

    private void menuHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHoaDonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHoaDonMouseClicked

    private void menuHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuHoaDonActionPerformed

    private void tkBieuDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkBieuDoActionPerformed
        // TODO add your handling code here:
        GD_ThongKeBieuDo uiTK = new GD_ThongKeBieuDo();
        this.setVisible(false);
        uiTK.setVisible(true);
    }//GEN-LAST:event_tkBieuDoActionPerformed

    private void menuThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuThongKeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuThongKeMouseClicked

    private void menuThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThongKeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_QuanLyDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_QuanLyDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_QuanLyDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_QuanLyDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_QuanLyDichVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DatPhong;
//    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuBar Menu1;
    private javax.swing.JMenuItem PhongDangSuDung;
    private javax.swing.JMenuItem QuanLyLoaiPhong;
    private javax.swing.JMenuItem QuanLyPhong;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxDonVi;
    private javax.swing.JComboBox<String> cbxLDV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
//    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JLabel lblDSLP;
    private javax.swing.JLabel lblTenNVLogin;
    private javax.swing.JMenu menuDichVu;
    private javax.swing.JMenu menuHoaDon;
    private javax.swing.JMenu menuKhachHang;
    private javax.swing.JMenu menuNhanVien;
    private javax.swing.JMenu menuPhong;
    private javax.swing.JMenu menuThongKe;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlDSNV;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlTTNV;
    private javax.swing.JMenuItem quanLyDonVi;
    private javax.swing.JMenuItem quanLyHoaDon;
    private javax.swing.JMenuItem quanLyKH;
    private javax.swing.JMenuItem quanLyLoaiDV;
    private javax.swing.JMenuItem quanLyNhanVien;
    private javax.swing.JMenuItem quanlyDV;
    private javax.swing.JScrollPane scrollDSDV;
    private javax.swing.JTable tblDSDV;
    private javax.swing.JMenuItem tkBieuDo;
    private javax.swing.JTextField txtGiaDV;
    private javax.swing.JTextField txtMaDV;
    private javax.swing.JTextField txtSoLuongTon;
    private javax.swing.JTextField txtTenDV;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
